import type {
  IngredientGroup,
  IngredientItem,
  Recipe,
  RecipeStep,
} from "@/lib/types";
import { findDemoCategory } from "@/lib/demo-data/categories";

/**
 * Eksempeloppskrifter brukt i demo-modus (når Supabase ikke er konfigurert)
 * og som kilde til scripts/seed.ts, som laster akkurat dette innholdet inn
 * i din ekte Supabase-database. Alle mengder er realistiske hjemmelagde
 * porsjoner – ingen lorem ipsum.
 */

let itemCounter = 0;
function item(
  amount: string | null,
  unit: string | null,
  name: string,
  note: string | null = null,
): IngredientItem {
  itemCounter += 1;
  return { id: `ing-${itemCounter}`, amount, unit, name, note, sortOrder: itemCounter };
}

let groupCounter = 0;
function group(title: string | null, items: IngredientItem[]): IngredientGroup {
  groupCounter += 1;
  return { id: `grp-${groupCounter}`, title, sortOrder: groupCounter, items };
}

let stepCounter = 0;
function stepsFor(groupTitle: string | null, texts: string[]): RecipeStep[] {
  return texts.map((text, i) => {
    stepCounter += 1;
    return {
      id: `step-${stepCounter}`,
      groupTitle,
      stepNumber: i + 1,
      text,
      sortOrder: stepCounter,
    };
  });
}

function img(file: string) {
  return `/images/recipes/${file}`;
}

export const demoRecipes: Recipe[] = [
  {
    id: "rec-salsiccia-pasta",
    slug: "kremet-salsiccia-pasta",
    title: "Kremet salsiccia-pasta",
    description:
      "Rask hverdagspasta med italiensk pølse, en kremet tomatsaus og masse parmesan. Klar på under 40 minutter.",
    heroImageUrl: img("salsiccia-pasta.jpg"),
    heroImageAlt: "Rigatoni i kremet tomatsaus med salsiccia og parmesan",
    images: [],
    category: findDemoCategory("pasta") ?? null,
    tags: [
      { id: "tag-italiensk", slug: "italiensk", name: "Italiensk" },
      { id: "tag-hverdag", slug: "hverdagsmiddag", name: "Hverdagsmiddag" },
      { id: "tag-comfort", slug: "comfort-food", name: "Comfort food" },
    ],
    servings: 4,
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    totalTimeMinutes: 40,
    difficulty: "middels",
    ingredientGroups: [
      group(null, [
        item("400", "g", "rigatoni"),
        item("3", "stk", "italiensk salsiccia", "ca. 400 g, skinn fjernet"),
        item("1", "stk", "gul løk", "finhakket"),
        item("3", "fedd", "hvitløk", "finhakket"),
        item("2", "ss", "tomatpuré"),
        item("2", "dl", "kremfløte"),
        item("1", "dl", "tørr hvitvin", "valgfritt"),
        item("50", "g", "parmesan", "finrevet, pluss ekstra til servering"),
        item("1", "ss", "olivenolje"),
        item("1", "ts", "chiliflak"),
        item(null, null, "salt og pepper", "etter smak"),
        item("1", "håndfull", "fersk basilikum"),
      ]),
    ],
    steps: stepsFor(null, [
      "Kok pastaen i godt saltet vann til den er al dente. Ta vare på ca. 2 dl av kokevannet før du heller av.",
      "Varm olivenolje i en stor stekepanne på middels-høy varme. Ha i salsiccia og stek til den er gjennomstekt og har fått god farge, mens du smuldrer den opp med en stekespade.",
      "Ha i løk og hvitløk, og stek i 3–4 minutter til løken er blank.",
      "Rør inn tomatpuré og chiliflak, og la det steke med i ett minutt.",
      "Hell i hvitvin (hvis du bruker) og la det koke inn i ca. 1 minutt.",
      "Senk varmen, tilsett kremfløte og la sausen småkoke i 3–4 minutter til den tykner litt.",
      "Rør inn parmesan til sausen er jevn og blank.",
      "Vend den kokte pastaen inn i sausen, og tilsett litt kokevann etter behov til konsistensen er kremet og dekker pastaen godt.",
      "Smak til med salt og pepper. Server umiddelbart med frisk basilikum og ekstra parmesan.",
    ]),
    notes:
      "Fungerer også fint med vanlig grillpølse eller italiensk pølse fra kjøttdisken dersom du ikke får tak i salsiccia.",
    tips: "Spar alltid litt kokevann fra pastaen – stivelsen gjør sausen kremet uten at du trenger mer fløte.",
    source: null,
    isPublished: true,
    isFeatured: true,
    featuredSortOrder: null,
    favoritedByAdmin: false,
    ratingSum: 0,
    ratingCount: 0,
    createdAt: "2026-08-20T18:00:00.000Z",
    updatedAt: "2026-08-20T18:00:00.000Z",
  },
  {
    id: "rec-napolitansk-pizza",
    slug: "napolitansk-pizza",
    title: "Napolitansk pizza",
    description:
      "Tynn, luftig bunn med sprø kant, San Marzano-tomater og bøffelmozzarella – slik de gjør det i Napoli.",
    heroImageUrl: img("napolitansk-pizza.jpg"),
    heroImageAlt: "Napolitansk pizza med mozzarella og fersk basilikum",
    images: [],
    category: findDemoCategory("pizza") ?? null,
    tags: [
      { id: "tag-italiensk", slug: "italiensk", name: "Italiensk" },
      { id: "tag-helgemat", slug: "helgemat", name: "Helgemat" },
      { id: "tag-ovnsbakt", slug: "ovnsbakt", name: "Ovnsbakt" },
    ],
    servings: 4,
    prepTimeMinutes: 30,
    cookTimeMinutes: 10,
    totalTimeMinutes: 210,
    difficulty: "avansert",
    ingredientGroups: [
      group("Deig", [
        item("500", "g", "tipo 00-mel", "eller fint hvetemel"),
        item("325", "ml", "lunkent vann"),
        item("10", "g", "salt"),
        item("3", "g", "tørrgjær"),
        item("1", "ts", "honning"),
      ]),
      group("Topping (for 4 pizzaer)", [
        item("400", "g", "hermetiske hele tomater", "moset for hånd"),
        item("1", "ts", "salt"),
        item("250", "g", "fersk bøffelmozzarella", "i biter"),
        item("4", "ss", "olivenolje"),
        item(null, null, "fersk basilikum"),
        item(null, null, "havsalt"),
      ]),
    ],
    steps: [
      ...stepsFor("Deig", [
        "Løs opp gjær og honning i det lunkne vannet.",
        "Bland mel og salt i en stor bolle. Hell i vannblandingen og bland til en kladdete deig.",
        "Elt deigen for hånd i 10 minutter, eller i kjøkkenmaskin med eltekrok i 6–7 minutter, til den er smidig og elastisk.",
        "Legg deigen i en oljet bolle, dekk til, og la den heve i romtemperatur i 2 timer til den er doblet i størrelse.",
        "Del deigen i 4 emner (ca. 200 g hver), form til kuler, og la dem etterheve tildekket i 30 minutter.",
      ]),
      ...stepsFor("Steking", [
        "Sett ovnen, helst med pizzastein eller pizzastål, på høyeste temperatur (minst 275 °C) og la den bli skikkelig varm i minst 45 minutter.",
        "Bland moste tomater med salt til pizzasaus.",
        "Press eller kjevle ut ett deigemne til en tynn bunn med litt tykkere kant.",
        "Smør på et tynt lag tomatsaus, fordel mozzarella utover, og drypp over litt olivenolje.",
        "Stek pizzaen i 90 sekunder til 4 minutter, avhengig av ovn, til bunnen har fått mørke flekker og osten bobler.",
        "Topp med fersk basilikum og et dryss havsalt rett før servering.",
      ]),
    ],
    notes:
      "Jo varmere ovn, jo mer autentisk napolitansk resultat – en pizzastein eller et pizzastål gjør stor forskjell.",
    tips: "Deigen blir enda bedre av å heve sakte i kjøleskap i 24 timer i stedet for 2 timer i romtemperatur.",
    source: null,
    isPublished: true,
    isFeatured: false,
    featuredSortOrder: null,
    favoritedByAdmin: true,
    ratingSum: 0,
    ratingCount: 0,
    createdAt: "2026-08-10T18:00:00.000Z",
    updatedAt: "2026-08-10T18:00:00.000Z",
  },
  {
    id: "rec-greske-svinespyd",
    slug: "gresk-grillet-svinekjott",
    title: "Gresk grillet svinekjøtt",
    description:
      "Sitron- og oreganomarinert svinespyd rett fra grillen, servert i lunt pitabrød med tzatziki og friske grønnsaker.",
    heroImageUrl: img("greske-svinespyd.jpg"),
    heroImageAlt: "Grillede svinespyd servert med pitabrød og tzatziki",
    images: [],
    category: findDemoCategory("kjott") ?? null,
    tags: [
      { id: "tag-gresk", slug: "gresk", name: "Gresk" },
      { id: "tag-grillmat", slug: "grillmat", name: "Grillmat" },
      { id: "tag-sommer", slug: "sommer", name: "Sommer" },
    ],
    servings: 4,
    prepTimeMinutes: 20,
    cookTimeMinutes: 10,
    totalTimeMinutes: 150,
    difficulty: "middels",
    ingredientGroups: [
      group("Marinade og kjøtt", [
        item("800", "g", "svinekam", "i terninger, ca. 3 cm"),
        item("4", "ss", "olivenolje"),
        item("2", "stk", "sitroner", "saften"),
        item("4", "fedd", "hvitløk", "finhakket"),
        item("2", "ts", "tørket oregano"),
        item("1", "ts", "spisskummen"),
        item("1", "ts", "salt"),
        item("½", "ts", "nykvernet pepper"),
      ]),
      group("Servering", [
        item("4", "stk", "pitabrød"),
        item("2", "dl", "tzatziki"),
        item("1", "stk", "rødløk", "i tynne ringer"),
        item("2", "stk", "tomater", "i båter"),
        item(null, null, "fersk persille"),
      ]),
    ],
    steps: stepsFor(null, [
      "Bland olivenolje, sitronsaft, hvitløk, oregano, spisskummen, salt og pepper i en stor bolle.",
      "Ha i svinekjøttet og bland godt slik at alle bitene er dekket av marinaden.",
      "Dekk til og la marinere i kjøleskap i minst 2 timer, gjerne over natten.",
      "Tre kjøttet på grillspyd (bruk metallspyd eller trespyd som er bløtlagt i vann).",
      "Varm opp grillen til høy, direkte varme.",
      "Grill spydene i 8–10 minutter, og vend jevnlig, til kjøttet er godt stekt og har fått en fin, mørk overflate.",
      "La kjøttet hvile i 5 minutter før servering.",
      "Server i lune pitabrød med tzatziki, rødløk, tomat og frisk persille.",
    ]),
    notes:
      "Kan også stekes i grillpanne eller under ovnens grillelement dersom du ikke har utegrill tilgjengelig.",
    tips: "Jo lenger kjøttet marinerer, jo mørere og mer smakfullt blir resultatet – over natten gir det beste resultatet.",
    source: null,
    isPublished: true,
    isFeatured: false,
    featuredSortOrder: null,
    favoritedByAdmin: false,
    ratingSum: 0,
    ratingCount: 0,
    createdAt: "2026-07-28T18:00:00.000Z",
    updatedAt: "2026-07-28T18:00:00.000Z",
  },
  {
    id: "rec-kylling-parmesan",
    slug: "kylling-parmesan",
    title: "Kylling parmesan",
    description:
      "Panert kyllingfilet med sprø panko-skorpe, god tomatsaus og smeltet mozzarella – en amerikansk-italiensk favoritt.",
    heroImageUrl: img("kylling-parmesan.jpg"),
    heroImageAlt: "Ovnsbakt kylling parmesan med smeltet ost og tomatsaus",
    images: [],
    category: findDemoCategory("kylling") ?? null,
    tags: [
      { id: "tag-italiensk-amerikansk", slug: "italiensk-amerikansk", name: "Italiensk-amerikansk" },
      { id: "tag-ovnsrett", slug: "ovnsrett", name: "Ovnsrett" },
      { id: "tag-familiemiddag", slug: "familiemiddag", name: "Familiemiddag" },
    ],
    servings: 4,
    prepTimeMinutes: 20,
    cookTimeMinutes: 25,
    totalTimeMinutes: 45,
    difficulty: "middels",
    ingredientGroups: [
      group(null, [
        item("4", "stk", "kyllingfileter"),
        item("1", "dl", "hvetemel"),
        item("2", "stk", "egg", "pisket"),
        item("2", "dl", "panko"),
        item("50", "g", "parmesan", "finrevet, pluss ekstra til topping"),
        item("1", "ts", "tørket oregano"),
        item("4", "dl", "god tomatsaus", "hjemmelaget eller kjøpt"),
        item("200", "g", "mozzarella", "i skiver"),
        item("3", "ss", "olivenolje"),
        item(null, null, "salt og pepper", "etter smak"),
        item(null, null, "fersk basilikum", "til servering"),
      ]),
    ],
    steps: stepsFor(null, [
      "Sett ovnen på 220 °C varmluft.",
      "Legg kyllingfiletene mellom to ark plastfolie og bank dem jevnt til ca. 1,5 cm tykkelse.",
      "Krydre kyllingen med salt og pepper.",
      "Sett opp tre paneringsstasjoner: mel i én, pisket egg i én, og panko blandet med parmesan og oregano i den tredje.",
      "Vend hver kyllingfilet først i mel, så i egg, og til slutt i panko-blandingen. Trykk godt slik at paneringen fester seg.",
      "Varm olivenolje i en ovnsfast stekepanne på middels-høy varme.",
      "Stek kyllingen i 3–4 minutter per side til gyllen og sprø.",
      "Ha en skje tomatsaus over hver filet, legg på mozzarella, og sett pannen i ovnen i 10–12 minutter til osten bobler og kyllingen er gjennomstekt (kjernetemperatur 74 °C).",
      "Dryss over ekstra parmesan og fersk basilikum. Server med resten av tomatsausen og gjerne spaghetti eller en grønn salat.",
    ]),
    notes: "Bruk et steketermometer for å være sikker på at kyllingen er gjennomstekt uten å bli tørr.",
    tips: "Panér gjerne kyllingen en time i forveien og sett den kaldt – det gir en sprøere overflate når den stekes.",
    source: null,
    isPublished: true,
    isFeatured: true,
    featuredSortOrder: null,
    favoritedByAdmin: false,
    ratingSum: 0,
    ratingCount: 0,
    createdAt: "2026-07-15T18:00:00.000Z",
    updatedAt: "2026-07-15T18:00:00.000Z",
  },
  {
    id: "rec-kjottboller-tomatsaus",
    slug: "kjottboller-i-tomatsaus",
    title: "Kjøttboller i tomatsaus",
    description:
      "Møre, hjemmelagde kjøttboller som småkoker i en rik tomatsaus med hvitløk og fersk basilikum.",
    heroImageUrl: img("kjottboller-tomatsaus.jpg"),
    heroImageAlt: "Kjøttboller i tomatsaus toppet med basilikum",
    images: [],
    category: findDemoCategory("kjott") ?? null,
    tags: [
      { id: "tag-italiensk", slug: "italiensk", name: "Italiensk" },
      { id: "tag-hverdag", slug: "hverdagsmiddag", name: "Hverdagsmiddag" },
      { id: "tag-comfort", slug: "comfort-food", name: "Comfort food" },
    ],
    servings: 4,
    prepTimeMinutes: 25,
    cookTimeMinutes: 40,
    totalTimeMinutes: 65,
    difficulty: "middels",
    ingredientGroups: [
      group("Kjøttboller", [
        item("500", "g", "kjøttdeig", "blanding av svin og storfe"),
        item("1", "stk", "egg"),
        item("1", "dl", "brødrasp"),
        item("1", "dl", "melk"),
        item("1", "stk", "gul løk", "finrevet"),
        item("2", "fedd", "hvitløk", "finhakket"),
        item("2", "ss", "fersk persille", "finhakket"),
        item("1", "ts", "salt"),
        item("½", "ts", "pepper"),
        item("¼", "ts", "muskatnøtt"),
        item("2", "ss", "olivenolje", "til steking"),
      ]),
      group("Tomatsaus", [
        item("2", "bokser", "hermetiske hakkede tomater", "400 g hver"),
        item("1", "stk", "gul løk", "finhakket"),
        item("3", "fedd", "hvitløk", "finhakket"),
        item("1", "ss", "tomatpuré"),
        item("1", "ts", "tørket oregano"),
        item("1", "ts", "sukker"),
        item("2", "ss", "olivenolje"),
        item(null, null, "salt og pepper", "etter smak"),
        item(null, null, "fersk basilikum"),
      ]),
    ],
    steps: [
      ...stepsFor("Kjøttboller", [
        "Bland brødrasp og melk i en bolle og la det svelle i 5 minutter.",
        "Ha kjøttdeig, egg, finrevet løk, hvitløk, persille, salt, pepper og muskat i bollen, og bland godt sammen med hendene til en jevn farse.",
        "Trill farsen til jevne kjøttboller, ca. 3 cm i diameter.",
        "Varm olivenolje i en stor gryte eller dyp stekepanne, og brun kjøttbollene på middels-høy varme til de har fin farge på alle sider. De trenger ikke være gjennomstekt ennå. Ta dem opp og sett til side.",
      ]),
      ...stepsFor("Tomatsaus", [
        "Ha litt mer olje i samme gryte, og fres løk og hvitløk til løken er blank.",
        "Rør inn tomatpuré og la det steke med i ett minutt.",
        "Tilsett hakkede tomater, oregano og sukker, og la sausen småkoke i 10 minutter.",
        "Ha kjøttbollene tilbake i sausen, og la det hele småkoke videre i 15–20 minutter til kjøttbollene er gjennomstekt og sausen har tyknet.",
        "Smak til med salt og pepper, og topp med fersk basilikum før servering.",
      ]),
    ],
    notes:
      "Perfekt sammen med spaghetti, kremet polenta eller godt brød til å dyppe i sausen.",
    tips: "Ikke overarbeid kjøttfarsen – bland akkurat til ingrediensene er fordelt for de møreste kjøttbollene.",
    source: null,
    isPublished: true,
    isFeatured: true,
    featuredSortOrder: null,
    favoritedByAdmin: true,
    ratingSum: 0,
    ratingCount: 0,
    createdAt: "2026-06-30T18:00:00.000Z",
    updatedAt: "2026-06-30T18:00:00.000Z",
  },
  {
    id: "rec-troffelpasta",
    slug: "troffelpasta",
    title: "Trøffelpasta",
    description:
      "Rask, kremet pastarett med parmesan og trøffelolje – enkel nok til en hverdag, fin nok til en festmiddag.",
    heroImageUrl: img("troffelpasta.jpg"),
    heroImageAlt: "Tagliatelle i kremet trøffelsaus med parmesan",
    images: [],
    category: findDemoCategory("pasta") ?? null,
    tags: [
      { id: "tag-italiensk", slug: "italiensk", name: "Italiensk" },
      { id: "tag-rask", slug: "rask-middag", name: "Rask middag" },
      { id: "tag-fest", slug: "festmiddag", name: "Festmiddag" },
    ],
    servings: 4,
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    totalTimeMinutes: 30,
    difficulty: "enkel",
    ingredientGroups: [
      group(null, [
        item("350", "g", "tagliatelle", "eller annen bred pasta"),
        item("40", "g", "smør"),
        item("2", "fedd", "hvitløk", "finhakket"),
        item("2", "dl", "kremfløte"),
        item("60", "g", "parmesan", "finrevet, pluss ekstra til servering"),
        item("2-3", "ts", "trøffelolje", "etter smak"),
        item("20", "g", "fersk eller hermetisert trøffel", "tynt skivet, valgfritt"),
        item(null, null, "salt og nykvernet pepper", "etter smak"),
        item(null, null, "fersk gressløk", "finhakket"),
      ]),
    ],
    steps: stepsFor(null, [
      "Kok pastaen i godt saltet vann til al dente. Ta vare på litt kokevann før avhelling.",
      "Smelt smør i en stor stekepanne på middels varme. Ha i hvitløk og stek i ett minutt til det dufter, uten å la det ta farge.",
      "Hell i kremfløte og la det småkoke i 2–3 minutter til det tykner lett.",
      "Rør inn parmesan litt etter litt til sausen er jevn og blank.",
      "Vend den kokte pastaen inn i sausen, og tilsett litt kokevann etter behov for en kremet konsistens.",
      "Ta pannen av varmen og rør inn trøffelolje etter smak.",
      "Smak til med salt og pepper, og fordel eventuelt fersk trøffel over.",
      "Server umiddelbart med ekstra parmesan og finhakket gressløk.",
    ]),
    notes: "Ekte fersk trøffel er valgfritt og sesongbasert – trøffelolje alene gir en fantastisk smak og duft.",
    tips: "Bruk trøffelolje helt til slutt, aldri under koking – varmen bryter ned den flyktige aromaen.",
    source: null,
    isPublished: true,
    isFeatured: false,
    featuredSortOrder: null,
    favoritedByAdmin: false,
    ratingSum: 0,
    ratingCount: 0,
    createdAt: "2026-06-10T18:00:00.000Z",
    updatedAt: "2026-06-10T18:00:00.000Z",
  },
  {
    id: "rec-crispy-potatoes",
    slug: "crispy-potatoes-med-aioli",
    title: "Crispy potatoes med aioli-dip",
    description:
      "Flate, sprø ovnsbakte poteter med røkt paprika og rosmarin, servert med en rask hvitløksaioli.",
    heroImageUrl: img("crispy-potatoes.jpg"),
    heroImageAlt: "Sprø ovnsbakte poteter med aioli-dip og rosmarin",
    images: [],
    category: findDemoCategory("tilbehor") ?? null,
    tags: [
      { id: "tag-tilbehor", slug: "tilbehor", name: "Tilbehør" },
      { id: "tag-sprott", slug: "sprott", name: "Sprøtt" },
      { id: "tag-fest", slug: "fest", name: "Fest" },
    ],
    servings: 4,
    prepTimeMinutes: 15,
    cookTimeMinutes: 40,
    totalTimeMinutes: 55,
    difficulty: "enkel",
    ingredientGroups: [
      group("Poteter", [
        item("1", "kg", "små faste poteter"),
        item("3", "ss", "olivenolje"),
        item("2", "ts", "grovt salt"),
        item("1", "ts", "røkt paprikapulver"),
        item("½", "ts", "hvitløkspulver"),
        item(null, null, "fersk rosmarin", "grovhakket"),
      ]),
      group("Aioli-dip", [
        item("1", "dl", "god majones"),
        item("2", "fedd", "hvitløk", "finrevet"),
        item("1", "ss", "sitronsaft"),
        item("½", "ts", "salt"),
      ]),
    ],
    steps: stepsFor(null, [
      "Sett ovnen på 220 °C varmluft.",
      "Kok potetene i saltet vann i 10–12 minutter til de er akkurat møre. Hell av vannet og la dem dampe tørre.",
      "Legg potetene på en bakeplate kledd med bakepapir, og press hver potet lett flat med bunnen av et glass.",
      "Dryss over olivenolje, salt, røkt paprika og hvitløkspulver.",
      "Stek potetene i ovnen i 30–35 minutter til de er gyldne og sprø i kantene. Snu dem gjerne halvveis.",
      "Rør sammen majones, hvitløk, sitronsaft og salt til aioli-dippen mens potetene steker.",
      "Dryss frisk rosmarin over potetene rett før servering, og server varme med aiolien ved siden av.",
    ]),
    notes: "Fungerer utmerket som tilbehør til grillmat, eller som snacks til en hyggekveld.",
    tips: "Å flate ut potetene før steking gir mye mer sprø overflate enn å steke dem hele.",
    source: null,
    isPublished: true,
    isFeatured: false,
    featuredSortOrder: null,
    favoritedByAdmin: false,
    ratingSum: 0,
    ratingCount: 0,
    createdAt: "2026-05-20T18:00:00.000Z",
    updatedAt: "2026-05-20T18:00:00.000Z",
  },
  {
    id: "rec-proteinpannekaker",
    slug: "proteinpannekaker",
    title: "Proteinpannekaker",
    description:
      "Mettende frokostpannekaker med cottage cheese og havregryn – enkle å blende sammen på en travel morgen.",
    heroImageUrl: img("proteinpannekaker.jpg"),
    heroImageAlt: "Stabel med proteinpannekaker toppet med bær og yoghurt",
    images: [],
    category: findDemoCategory("frokost") ?? null,
    tags: [
      { id: "tag-frokost", slug: "frokost", name: "Frokost" },
      { id: "tag-protein", slug: "protein", name: "Protein" },
      { id: "tag-rask", slug: "rask", name: "Rask" },
    ],
    servings: 2,
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    totalTimeMinutes: 25,
    difficulty: "enkel",
    ingredientGroups: [
      group(null, [
        item("3", "stk", "egg"),
        item("2", "dl", "cottage cheese", "eller kesam"),
        item("1", "dl", "havregryn"),
        item("1", "skje", "proteinpulver", "ca. 30 g, nøytral eller vanilje"),
        item("1", "ts", "bakepulver"),
        item("½", "ts", "kanel"),
        item("1", "ts", "vaniljeekstrakt"),
        item(null, null, "nøytral olje eller smør", "til steking"),
        item(null, null, "bær, gresk yoghurt og lønnesirup", "til servering"),
      ]),
    ],
    steps: stepsFor(null, [
      "Ha egg, cottage cheese, havregryn, proteinpulver, bakepulver, kanel og vaniljeekstrakt i en blender.",
      "Blend til en jevn, tykk røre. La røren hvile i 5 minutter slik at havregrynene svulmer litt.",
      "Varm en stekepanne på middels varme med litt olje eller smør.",
      "Hell små, jevne porsjoner røre i pannen, ca. 1/4 dl per pannekake.",
      "Stek i 2–3 minutter til det dannes bobler på overflaten og undersiden er gyllen.",
      "Snu forsiktig og stek videre i 1–2 minutter på den andre siden.",
      "Server varme med friske bær, en klatt gresk yoghurt og eventuelt litt lønnesirup.",
    ]),
    notes: "Røren kan også lages kvelden før og oppbevares kaldt til neste morgen.",
    tips: "Bruk lav-middels varme og ikke for store pannekaker – da unngår du at de brenner seg utenpå før de er ferdige inni.",
    source: null,
    isPublished: true,
    isFeatured: false,
    featuredSortOrder: null,
    favoritedByAdmin: false,
    ratingSum: 0,
    ratingCount: 0,
    createdAt: "2026-05-02T18:00:00.000Z",
    updatedAt: "2026-05-02T18:00:00.000Z",
  },
];

export function findDemoRecipe(slug: string): Recipe | undefined {
  return demoRecipes.find((r) => r.slug === slug);
}
