import type { Season, SeasonalIngredient } from "@/lib/types";

/**
 * Samme sesongsett som seedes inn i Supabase av scripts/seed.ts – se
 * supabase/migrations/0014_seasons.sql + 0016_season_ingredient_richness.sql
 * for tabellstruktur. Holdes som ren TypeScript-data (ikke SQL) slik at
 * demo-modus og seeding deler én kilde til sannhet, akkurat som
 * lib/demo-data/guide-categories.ts/guides.ts.
 *
 * Seks norske sesonger (ikke fire generiske årstider, se spesifikasjonens
 * punkt 7) som til sammen dekker alle 12 månedene uten overlapp SEG
 * IMELLOM. Enkeltråvarer under kan likevel ha sesong-/topp-vinduer som
 * strekker seg over sesonggrensen (rabarbra vår->forsommer, kantareller
 * sensommer->høst, skrei vinter->vår osv.) – se filheaderen til
 * SeasonalIngredient i lib/types.ts.
 */
export const demoSeasons: Season[] = [
  {
    id: "season-var",
    slug: "var",
    nameNo: "Vår",
    nameEn: "Spring",
    months: [3, 4, 5],
    introNo:
      "De første grønne skuddene etter vinteren. Ramsløk i skogbunnen, sprø reddiker, og skrei som fortsatt er på sitt beste.",
    introEn:
      "The first green shoots after winter. Wild garlic in the forest floor, crisp radishes, and Arctic cod still at its best.",
    sortOrder: 1,
    isPublished: true,
    createdAt: "2026-08-27T00:00:00.000Z",
    updatedAt: "2026-08-27T00:00:00.000Z",
  },
  {
    id: "season-forsommer",
    slug: "forsommer",
    nameNo: "Forsommer",
    nameEn: "Early summer",
    months: [6],
    introNo:
      "Den korte, intense perioden hvor norske jordbær endelig kommer, nypoteter er søte som aldri senere, og asparges er på sitt beste.",
    introEn:
      "The short, intense stretch when Norwegian strawberries finally arrive, new potatoes are as sweet as they'll ever be, and asparagus is at its peak.",
    sortOrder: 2,
    isPublished: true,
    createdAt: "2026-08-27T00:00:00.000Z",
    updatedAt: "2026-08-27T00:00:00.000Z",
  },
  {
    id: "season-sommer",
    slug: "sommer",
    nameNo: "Sommer",
    nameEn: "Summer",
    months: [7],
    introNo: "Bærsesongens høydepunkt, og hagene begynner å gi fra seg det de har lovet siden mai.",
    introEn: "The peak of berry season, and the gardens finally deliver on what they've promised since May.",
    sortOrder: 3,
    isPublished: true,
    createdAt: "2026-08-27T00:00:00.000Z",
    updatedAt: "2026-08-27T00:00:00.000Z",
  },
  {
    id: "season-sensommer",
    slug: "sensommer",
    nameNo: "Sensommer",
    nameEn: "Late summer",
    months: [8, 9],
    introNo:
      "September er måneden hvor sommerens grønnsaker møter høstens sopp, krabbe og lam. Årets korteste, mest overdådige vindu.",
    introEn:
      "September is the month when summer's vegetables meet autumn's mushrooms, crab and lamb. The year's shortest, most abundant window.",
    sortOrder: 4,
    isPublished: true,
    createdAt: "2026-08-27T00:00:00.000Z",
    updatedAt: "2026-08-27T00:00:00.000Z",
  },
  {
    id: "season-host",
    slug: "host",
    nameNo: "Høst",
    nameEn: "Autumn",
    months: [10, 11],
    introNo:
      "Hummerfisket starter 1. oktober. Sopp, vilt, skalldyr, epler og rotgrønnsaker gjør høsten til en av årets rikeste perioder på tallerkenen.",
    introEn:
      "Norwegian lobster fishing opens on October 1st. Mushrooms, game, shellfish, apples and root vegetables make autumn one of the year's richest periods on the plate.",
    sortOrder: 5,
    isPublished: true,
    createdAt: "2026-08-27T00:00:00.000Z",
    updatedAt: "2026-08-27T00:00:00.000Z",
  },
  {
    id: "season-vinter",
    slug: "vinter",
    nameNo: "Vinter",
    nameEn: "Winter",
    months: [12, 1, 2],
    introNo:
      "En sterk sjømatsesong, med skrei fra januar, skjell og reker. Grønnkål som er blitt søtere av frosten, rotgrønnsaker fra lager, og sitrus fra sør på kjøkkenbenken.",
    introEn:
      "A strong seafood season, with Arctic cod from January, shellfish and prawns. Kale sweetened by the frost, stored root vegetables, and citrus from the south on the kitchen counter.",
    sortOrder: 6,
    isPublished: true,
    createdAt: "2026-08-27T00:00:00.000Z",
    updatedAt: "2026-08-27T00:00:00.000Z",
  },
];

export function findDemoSeason(slug: string): Season | undefined {
  return demoSeasons.find((s) => s.slug === slug);
}

/* Delte konstanter for å holde de ~80 råvare-objektene under mer lesbare –
 * ren stilistisk forenkling, ingen semantisk betydning. `TS` er tidspunktet
 * denne utvidelsen ble bygget, `VERIFIED` er datoen kildegrunnlaget sist
 * ble kontrollert (spesifikasjonens punkt 36). */
const TS = "2026-08-28T00:00:00.000Z";
const VERIFIED = "2026-08-28";

const GODFISK = "Norges sjømatråd (Godfisk)";
const FRUKT = "Opplysningskontoret for frukt og grønt";
const FRUKT_URL = "https://www.frukt.no/norsk-sesongkalender/";
const MATPRAT = "Matprat (Animalia)";
const FISKERIDIR = "Fiskeridirektoratet";
const SOPPFORBUND = "Norges sopp- og nyttevekstforbund";
const JAKT = "Miljødirektoratet (jakttider)";

export const demoSeasonalIngredients: SeasonalIngredient[] = [
  // ══════════════════════════ VÅR (spesifikasjonens punkt 9) ══════════════════════════
  {
    id: "ingr-ramslok",
    seasonId: "season-var",
    slug: "ramslok",
    nameNo: "Ramsløk",
    nameEn: "Wild garlic",
    aliases: ["ramsløk", "ramsløken", "villhvitløk"],
    category: "vegetable",
    originGroup: "skogen",
    origin: "norwegian",
    availableStartMonth: 4,
    availableEndMonth: 5,
    seasonStartMonth: 4,
    seasonEndMonth: 5,
    peakStartMonth: 4,
    peakEndMonth: 5,
    descriptionNo: "Skogbunnens hvitløk. Bruk rå i pesto eller finhakket over egg.",
    descriptionEn: "The forest floor's garlic. Use raw in pesto or finely chopped over eggs.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: "Kort norsk sesong, kun april-mai.",
    verifiedAt: VERIFIED,
    sortOrder: 1,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-asparges",
    seasonId: "season-var",
    slug: "asparges",
    nameNo: "Asparges",
    nameEn: "Asparagus",
    aliases: ["asparges", "grønn asparges"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 4,
    availableEndMonth: 7,
    seasonStartMonth: 5,
    seasonEndMonth: 6,
    peakStartMonth: 6,
    peakEndMonth: 6,
    descriptionNo: "Norsk asparges har en kort, intens sesong fra mai til juni.",
    descriptionEn: "Norwegian asparagus has a short, intense season from May to June.",
    seasonNoteNo:
      "Norsk asparges har en kort sesong, typisk fra mai til utpå juni. Utenfor denne perioden er asparges i norske butikker som regel importert.",
    seasonNoteEn:
      "Norwegian asparagus has a short season, typically from May into June. Outside this window, asparagus in Norwegian shops is usually imported.",
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 2,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-reddik",
    seasonId: "season-var",
    slug: "reddik",
    nameNo: "Reddiker",
    nameEn: "Radishes",
    aliases: ["reddik", "reddiker"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 3,
    availableEndMonth: 10,
    seasonStartMonth: 4,
    seasonEndMonth: 6,
    peakStartMonth: 5,
    peakEndMonth: 5,
    descriptionNo: "Sprø og mild tidlig i sesongen, får en skarpere smak utover sommeren.",
    descriptionEn: "Crisp and mild early in the season, developing a sharper bite as summer goes on.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 3,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-varlok",
    seasonId: "season-var",
    slug: "varlok",
    nameNo: "Vårløk",
    nameEn: "Spring onion",
    aliases: ["vårløk", "spring onion"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 4,
    availableEndMonth: 9,
    seasonStartMonth: 4,
    seasonEndMonth: 9,
    peakStartMonth: 5,
    peakEndMonth: 7,
    descriptionNo: "Mildere og søtere enn moden løk, med spiselig grønt blad.",
    descriptionEn: "Milder and sweeter than mature onion, with an edible green stalk.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 4,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-salat",
    seasonId: "season-var",
    slug: "salat",
    nameNo: "Salat",
    nameEn: "Lettuce",
    aliases: ["salat", "bladsalat", "hodesalat"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 5,
    availableEndMonth: 9,
    seasonStartMonth: 5,
    seasonEndMonth: 9,
    peakStartMonth: 6,
    peakEndMonth: 8,
    descriptionNo: "Norsk salat i butikk er et tydelig tegn på at sommeren er i gang.",
    descriptionEn: "Norwegian lettuce in shops is a clear sign summer has arrived.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 5,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-gresslok",
    seasonId: "season-var",
    slug: "gresslok",
    nameNo: "Gressløk",
    nameEn: "Chives",
    aliases: ["gressløk"],
    category: "herb",
    originGroup: "hagen",
    origin: "norwegian",
    availableStartMonth: 5,
    availableEndMonth: 9,
    seasonStartMonth: 5,
    seasonEndMonth: 9,
    peakStartMonth: 6,
    peakEndMonth: 8,
    descriptionNo: "Norsk krydderurt med skarp løksmak, best fersk rett før servering.",
    descriptionEn: "A Norwegian herb with a sharp onion flavor, best used fresh right before serving.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 6,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-rabarbra",
    seasonId: "season-var",
    slug: "rabarbra",
    nameNo: "Rabarbra",
    nameEn: "Rhubarb",
    aliases: ["rabarbra"],
    category: "fruit",
    originGroup: "hagen",
    origin: "norwegian",
    availableStartMonth: 5,
    availableEndMonth: 7,
    seasonStartMonth: 5,
    seasonEndMonth: 7,
    peakStartMonth: 5,
    peakEndMonth: 6,
    descriptionNo: "Topper akkurat idet våren går over i forsommer.",
    descriptionEn: "Peaks right as spring turns into early summer.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 7,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-skrei",
    seasonId: "season-var",
    slug: "skrei",
    nameNo: "Skrei",
    nameEn: "Arctic cod",
    aliases: ["skrei"],
    category: "fish",
    originGroup: "havet",
    origin: "norwegian",
    availableStartMonth: 1,
    availableEndMonth: 4,
    seasonStartMonth: 1,
    seasonEndMonth: 4,
    peakStartMonth: 2,
    peakEndMonth: 3,
    descriptionNo: "Den vandrende torsken fra Barentshavet. Har en klar, avgrenset sesong, i motsetning til vanlig torsk.",
    descriptionEn: "The migrating cod from the Barents Sea. Has a clear, limited season, unlike regular cod.",
    seasonNoteNo:
      "Skrei har en klar sesong fra januar til april, i motsetning til vanlig torsk som fiskes hele året. Norges sjømatråd trekker fram at sesongen avsluttes i april, mens makrellen samtidig kommer inn i norske farvann.",
    seasonNoteEn:
      "Skrei has a clear season from January to April, unlike regular cod which is fished year-round. The Norwegian Seafood Council notes that the season ends in April, just as mackerel arrives in Norwegian waters.",
    sourceName: GODFISK,
    sourceUrl: null,
    sourceNote: "Skreisesongen regnes fra januar til april.",
    verifiedAt: VERIFIED,
    sortOrder: 8,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-sei",
    seasonId: "season-var",
    slug: "sei",
    nameNo: "Sei",
    nameEn: "Saithe",
    aliases: ["sei"],
    category: "fish",
    originGroup: "havet",
    origin: "norwegian",
    availableStartMonth: 1,
    availableEndMonth: 12,
    seasonStartMonth: 3,
    seasonEndMonth: 5,
    peakStartMonth: 3,
    peakEndMonth: 4,
    descriptionNo: "Tilgjengelig store deler av året, men fremheves gjerne som en av vårens gode sjømatråvarer.",
    descriptionEn: "Available for much of the year, but often highlighted as one of spring's good seafood picks.",
    seasonNoteNo:
      "Norges sjømatråd trekker fram sei som en av vårens gode sjømatråvarer, sammen med rødspette og kveite.",
    seasonNoteEn:
      "The Norwegian Seafood Council highlights saithe as one of spring's good seafood choices, alongside plaice and halibut.",
    sourceName: GODFISK,
    sourceUrl: null,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 9,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-rodspette",
    seasonId: "season-var",
    slug: "rodspette",
    nameNo: "Rødspette",
    nameEn: "Plaice",
    aliases: ["rødspette", "spette"],
    category: "fish",
    originGroup: "havet",
    origin: "norwegian",
    availableStartMonth: 1,
    availableEndMonth: 12,
    seasonStartMonth: 3,
    seasonEndMonth: 6,
    peakStartMonth: 4,
    peakEndMonth: 5,
    descriptionNo: "En av de flate fiskene Norges sjømatråd trekker fram om våren.",
    descriptionEn: "One of the flatfish the Norwegian Seafood Council highlights in spring.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: GODFISK,
    sourceUrl: null,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 10,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-kveite",
    seasonId: "season-var",
    slug: "kveite",
    nameNo: "Kveite",
    nameEn: "Halibut",
    aliases: ["kveite", "halibut"],
    category: "fish",
    originGroup: "havet",
    origin: "norwegian",
    availableStartMonth: 1,
    availableEndMonth: 12,
    seasonStartMonth: 10,
    seasonEndMonth: 6,
    peakStartMonth: 11,
    peakEndMonth: 1,
    descriptionNo: "Tilgjengelig store deler av året, men fremheves særlig om våren, høsten og vinteren.",
    descriptionEn: "Available for much of the year, but especially highlighted in spring, autumn and winter.",
    seasonNoteNo:
      "Kveite regnes som en av vårens sjømatråvarer, men er også relevant utover høsten og vinteren. Sommeren er tradisjonelt en roligere periode.",
    seasonNoteEn:
      "Halibut is considered one of spring's seafood picks, but is also relevant through autumn and winter. Summer is traditionally a quieter period.",
    sourceName: GODFISK,
    sourceUrl: null,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 11,
    createdAt: TS,
    updatedAt: TS,
  },

  // ══════════════════════════ FORSOMMER (spesifikasjonens punkt 10) ══════════════════════════
  {
    id: "ingr-nypoteter",
    seasonId: "season-forsommer",
    slug: "nypoteter",
    nameNo: "Nypoteter",
    nameEn: "New potatoes",
    aliases: ["nypoteter", "nye poteter"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 6,
    availableEndMonth: 8,
    seasonStartMonth: 6,
    seasonEndMonth: 8,
    peakStartMonth: 6,
    peakEndMonth: 7,
    descriptionNo: "Tynnskallet og søte. Trenger knapt annet enn smør og salt.",
    descriptionEn: "Thin-skinned and sweet. They barely need more than butter and salt.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 1,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-nykal",
    seasonId: "season-forsommer",
    slug: "nykal",
    nameNo: "Nykål",
    nameEn: "Early cabbage",
    aliases: ["nykål", "tidligkål", "spisskål"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 6,
    availableEndMonth: 8,
    seasonStartMonth: 6,
    seasonEndMonth: 8,
    peakStartMonth: 7,
    peakEndMonth: 7,
    descriptionNo: "Mørere og mildere enn vinterkål, med løse, sprø blader.",
    descriptionEn: "More tender and mild than winter cabbage, with loose, crisp leaves.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 2,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-blomkal",
    seasonId: "season-forsommer",
    slug: "blomkal",
    nameNo: "Blomkål",
    nameEn: "Cauliflower",
    aliases: ["blomkål"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 6,
    availableEndMonth: 10,
    seasonStartMonth: 6,
    seasonEndMonth: 9,
    peakStartMonth: 7,
    peakEndMonth: 8,
    descriptionNo: "Norsk blomkål har en kortere, mer intens sesong enn den importerte varianten man finner resten av året.",
    descriptionEn: "Norwegian cauliflower has a shorter, more intense season than the imported version found the rest of the year.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 3,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-brokkoli",
    seasonId: "season-forsommer",
    slug: "brokkoli",
    nameNo: "Brokkoli",
    nameEn: "Broccoli",
    aliases: ["brokkoli"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 6,
    availableEndMonth: 10,
    seasonStartMonth: 6,
    seasonEndMonth: 9,
    peakStartMonth: 7,
    peakEndMonth: 8,
    descriptionNo: "Norsk brokkoli er søtere og mer sprø enn importert brokkoli utenfor sesong.",
    descriptionEn: "Norwegian broccoli is sweeter and crisper than imported broccoli out of season.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 4,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-brokkolini",
    seasonId: "season-forsommer",
    slug: "brokkolini",
    nameNo: "Brokkolini",
    nameEn: "Broccolini",
    aliases: ["brokkolini"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 6,
    availableEndMonth: 10,
    seasonStartMonth: 6,
    seasonEndMonth: 9,
    peakStartMonth: 7,
    peakEndMonth: 8,
    descriptionNo: "Slankere og mildere enn vanlig brokkoli, med spiselig stilk.",
    descriptionEn: "Slimmer and milder than regular broccoli, with an edible stalk.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 5,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-spinat",
    seasonId: "season-forsommer",
    slug: "spinat",
    nameNo: "Spinat",
    nameEn: "Spinach",
    aliases: ["spinat"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 5,
    availableEndMonth: 9,
    seasonStartMonth: 5,
    seasonEndMonth: 6,
    peakStartMonth: 5,
    peakEndMonth: 6,
    descriptionNo: "Har gjerne to kortere sesonger, vår og tidlig høst, siden varmen får planten til å skyte.",
    descriptionEn: "Tends to have two shorter seasons, spring and early autumn, since heat makes the plant bolt.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 6,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-jordbaer",
    seasonId: "season-forsommer",
    slug: "jordbaer",
    nameNo: "Jordbær",
    nameEn: "Strawberries",
    aliases: ["jordbær", "norske jordbær"],
    category: "berry",
    originGroup: "hagen",
    origin: "norwegian",
    availableStartMonth: 6,
    availableEndMonth: 8,
    seasonStartMonth: 6,
    seasonEndMonth: 8,
    peakStartMonth: 6,
    peakEndMonth: 7,
    descriptionNo: "Norske jordbær har hovedsesong fra juni til august.",
    descriptionEn: "Norwegian strawberries have their main season from June to August.",
    seasonNoteNo:
      "Norske jordbær har hovedsesong fra juni til august. Bær utenfor denne perioden er som regel importert.",
    seasonNoteEn:
      "Norwegian strawberries have their main season from June to August. Berries outside this window are usually imported.",
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 7,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-breiflabb",
    seasonId: "season-forsommer",
    slug: "breiflabb",
    nameNo: "Breiflabb",
    nameEn: "Monkfish",
    aliases: ["breiflabb"],
    category: "fish",
    originGroup: "havet",
    origin: "norwegian",
    availableStartMonth: 1,
    availableEndMonth: 12,
    seasonStartMonth: 6,
    seasonEndMonth: 9,
    peakStartMonth: 7,
    peakEndMonth: 8,
    descriptionNo: "Fast, hvit fisk uten bein midt i filéten, populær i gryter og supper.",
    descriptionEn: "Firm, white fish without bones down the middle of the fillet, popular in stews and soups.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: GODFISK,
    sourceUrl: null,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 8,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-lysing",
    seasonId: "season-forsommer",
    slug: "lysing",
    nameNo: "Lysing",
    nameEn: "Hake",
    aliases: ["lysing"],
    category: "fish",
    originGroup: "havet",
    origin: "norwegian",
    availableStartMonth: 1,
    availableEndMonth: 12,
    seasonStartMonth: 6,
    seasonEndMonth: 9,
    peakStartMonth: 7,
    peakEndMonth: 8,
    descriptionNo: "Mild, hvit fisk med fint, flakete kjøtt.",
    descriptionEn: "Mild, white fish with fine, flaky flesh.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: GODFISK,
    sourceUrl: null,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 9,
    createdAt: TS,
    updatedAt: TS,
  },

  // ══════════════════════════ SOMMER (spesifikasjonens punkt 11) ══════════════════════════
  {
    id: "ingr-sukkererter",
    seasonId: "season-sommer",
    slug: "sukkererter",
    nameNo: "Sukkererter",
    nameEn: "Snap peas",
    aliases: ["sukkererter"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 7,
    availableEndMonth: 9,
    seasonStartMonth: 7,
    seasonEndMonth: 9,
    peakStartMonth: 7,
    peakEndMonth: 8,
    descriptionNo: "Spises hele, med belg og alt, rett fra hagen eller kort dampet.",
    descriptionEn: "Eaten whole, pod and all, straight from the garden or lightly steamed.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 1,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-erter",
    seasonId: "season-sommer",
    slug: "erter",
    nameNo: "Grønne erter",
    nameEn: "Green peas",
    aliases: ["erter", "grønne erter"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 7,
    availableEndMonth: 9,
    seasonStartMonth: 7,
    seasonEndMonth: 8,
    peakStartMonth: 7,
    peakEndMonth: 8,
    descriptionNo: "Ferske norske erter har en kort sesong og en tydelig søtere smak enn frosne.",
    descriptionEn: "Fresh Norwegian peas have a short season and a noticeably sweeter taste than frozen.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 2,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-bonner",
    seasonId: "season-sommer",
    slug: "bonner",
    nameNo: "Bønner",
    nameEn: "Beans",
    aliases: ["bønner", "brytebønner", "vaksbønner"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 7,
    availableEndMonth: 9,
    seasonStartMonth: 7,
    seasonEndMonth: 9,
    peakStartMonth: 8,
    peakEndMonth: 8,
    descriptionNo: "Norske bønner i butikk er et av sensommerens tydeligste tegn.",
    descriptionEn: "Norwegian beans in shops are one of late summer's clearest signs.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 3,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-knutekal",
    seasonId: "season-sommer",
    slug: "knutekal",
    nameNo: "Knutekål",
    nameEn: "Kohlrabi",
    aliases: ["knutekål"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 7,
    availableEndMonth: 10,
    seasonStartMonth: 7,
    seasonEndMonth: 9,
    peakStartMonth: 8,
    peakEndMonth: 8,
    descriptionNo: "Mild, søtlig smak et sted mellom kål og reddik.",
    descriptionEn: "A mild, slightly sweet taste somewhere between cabbage and radish.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 4,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-agurk",
    seasonId: "season-sommer",
    slug: "agurk",
    nameNo: "Agurk",
    nameEn: "Cucumber",
    aliases: ["agurk", "slangeagurk"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 7,
    availableEndMonth: 9,
    seasonStartMonth: 7,
    seasonEndMonth: 9,
    peakStartMonth: 7,
    peakEndMonth: 8,
    descriptionNo: "Norsk agurk er sprøere og har mindre kjerner enn importert agurk.",
    descriptionEn: "Norwegian cucumber is crisper and has fewer seeds than imported cucumber.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 5,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-bringebaer",
    seasonId: "season-sommer",
    slug: "bringebaer",
    nameNo: "Bringebær",
    nameEn: "Raspberries",
    aliases: ["bringebær"],
    category: "berry",
    originGroup: "hagen",
    origin: "norwegian",
    availableStartMonth: 7,
    availableEndMonth: 9,
    seasonStartMonth: 7,
    seasonEndMonth: 9,
    peakStartMonth: 7,
    peakEndMonth: 8,
    descriptionNo: "Norske bringebær har en kort, intens sesong midtsommers.",
    descriptionEn: "Norwegian raspberries have a short, intense midsummer season.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 6,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-rips",
    seasonId: "season-sommer",
    slug: "rips",
    nameNo: "Rips",
    nameEn: "Redcurrants",
    aliases: ["rips", "solbær og rips"],
    category: "berry",
    originGroup: "hagen",
    origin: "norwegian",
    availableStartMonth: 7,
    availableEndMonth: 8,
    seasonStartMonth: 7,
    seasonEndMonth: 8,
    peakStartMonth: 7,
    peakEndMonth: 8,
    descriptionNo: "Syrlige bær, ofte brukt i gelé og saft.",
    descriptionEn: "Tart berries, often used for jelly and cordial.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 7,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-solbaer",
    seasonId: "season-sommer",
    slug: "solbaer",
    nameNo: "Solbær",
    nameEn: "Blackcurrants",
    aliases: ["solbær"],
    category: "berry",
    originGroup: "hagen",
    origin: "norwegian",
    availableStartMonth: 7,
    availableEndMonth: 8,
    seasonStartMonth: 7,
    seasonEndMonth: 8,
    peakStartMonth: 7,
    peakEndMonth: 8,
    descriptionNo: "Norges mest vitamin C-rike bær, med en kraftig, syrlig smak.",
    descriptionEn: "Norway's most vitamin C-rich berry, with a bold, tart flavor.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 8,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-stikkelsbaer",
    seasonId: "season-sommer",
    slug: "stikkelsbaer",
    nameNo: "Stikkelsbær",
    nameEn: "Gooseberries",
    aliases: ["stikkelsbær"],
    category: "berry",
    originGroup: "hagen",
    origin: "norwegian",
    availableStartMonth: 6,
    availableEndMonth: 7,
    seasonStartMonth: 6,
    seasonEndMonth: 7,
    peakStartMonth: 6,
    peakEndMonth: 7,
    descriptionNo: "Syrlige tidlig i sesongen, søtere når de er helt modne.",
    descriptionEn: "Tart early in the season, sweeter once fully ripe.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 9,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-moreller",
    seasonId: "season-sommer",
    slug: "moreller",
    nameNo: "Moreller",
    nameEn: "Sweet cherries",
    aliases: ["moreller", "søtkirsebær"],
    category: "fruit",
    originGroup: "hagen",
    origin: "norwegian",
    availableStartMonth: 7,
    availableEndMonth: 7,
    seasonStartMonth: 7,
    seasonEndMonth: 7,
    peakStartMonth: 7,
    peakEndMonth: 7,
    descriptionNo: "Kort norsk sesong, kjent fra fruktbygdene på Vestlandet.",
    descriptionEn: "A short Norwegian season, known from the fruit-growing districts of western Norway.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 10,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-kirsebaer",
    seasonId: "season-sommer",
    slug: "kirsebaer",
    nameNo: "Kirsebær",
    nameEn: "Cherries",
    aliases: ["kirsebær"],
    category: "fruit",
    originGroup: "hagen",
    origin: "norwegian",
    availableStartMonth: 7,
    availableEndMonth: 8,
    seasonStartMonth: 7,
    seasonEndMonth: 8,
    peakStartMonth: 7,
    peakEndMonth: 8,
    descriptionNo: "Norske kirsebær har en kort sesong og selges gjerne rett fra produsent.",
    descriptionEn: "Norwegian cherries have a short season and are often sold directly from the grower.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 11,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-blabaer",
    seasonId: "season-sommer",
    slug: "blabaer",
    nameNo: "Blåbær",
    nameEn: "Blueberries",
    aliases: ["blåbær", "villblåbær"],
    category: "berry",
    originGroup: "skogen",
    origin: "norwegian",
    availableStartMonth: 7,
    availableEndMonth: 9,
    seasonStartMonth: 7,
    seasonEndMonth: 9,
    peakStartMonth: 8,
    peakEndMonth: 8,
    descriptionNo: "Ville norske blåbær fra skogen har en mer intens smak enn dyrkede.",
    descriptionEn: "Wild Norwegian blueberries from the forest have a more intense flavor than cultivated ones.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 12,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-makrell",
    seasonId: "season-sommer",
    slug: "makrell",
    nameNo: "Makrell",
    nameEn: "Mackerel",
    aliases: ["makrell"],
    category: "fish",
    originGroup: "havet",
    origin: "norwegian",
    availableStartMonth: 5,
    availableEndMonth: 10,
    seasonStartMonth: 5,
    seasonEndMonth: 10,
    peakStartMonth: 8,
    peakEndMonth: 10,
    descriptionNo: "Kommer inn mot norskekysten fra rundt mai. Blir stadig fetere gjennom sommeren og høsten.",
    descriptionEn: "Arrives off the Norwegian coast from around May. Grows fattier through summer and autumn.",
    seasonNoteNo:
      "Makrellen kommer inn mot norskekysten fra rundt mai og er en klassisk sommerfisk. Fettinnholdet stiger utover sesongen, fra rundt 3 prosent om våren til opp mot 30 prosent om høsten, ifølge Norges sjømatråd.",
    seasonNoteEn:
      "Mackerel arrives off the Norwegian coast from around May and is a classic summer fish. Its fat content rises through the season, from around 3 percent in spring to up to 30 percent in autumn, according to the Norwegian Seafood Council.",
    sourceName: GODFISK,
    sourceUrl: null,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 13,
    createdAt: TS,
    updatedAt: TS,
  },

  // ══════════════════════════ SENSOMMER (spesifikasjonens punkt 12) ══════════════════════════
  {
    id: "ingr-tomat",
    seasonId: "season-sensommer",
    slug: "tomat",
    nameNo: "Tomat",
    nameEn: "Tomato",
    aliases: ["tomat", "tomater", "cherrytomat", "cherrytomater"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 7,
    availableEndMonth: 9,
    seasonStartMonth: 7,
    seasonEndMonth: 9,
    peakStartMonth: 8,
    peakEndMonth: 9,
    descriptionNo: "Endelig modnet i sol, ikke i lastebil.",
    descriptionEn: "Finally ripened in the sun, not in a truck.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 1,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-mais",
    seasonId: "season-sensommer",
    slug: "mais",
    nameNo: "Mais",
    nameEn: "Corn",
    aliases: ["mais", "maiskolbe"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 8,
    availableEndMonth: 9,
    seasonStartMonth: 8,
    seasonEndMonth: 9,
    peakStartMonth: 8,
    peakEndMonth: 9,
    descriptionNo: "Norsk sukkermais bør spises kort tid etter høsting, før sukkeret omdannes til stivelse.",
    descriptionEn: "Norwegian sweetcorn is best eaten soon after harvest, before the sugars convert to starch.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 2,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-squash",
    seasonId: "season-sensommer",
    slug: "squash",
    nameNo: "Squash",
    nameEn: "Zucchini",
    aliases: ["squash", "sukkerbrødsquash", "zucchini"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 7,
    availableEndMonth: 9,
    seasonStartMonth: 7,
    seasonEndMonth: 9,
    peakStartMonth: 8,
    peakEndMonth: 8,
    descriptionNo: "Mild smak, tar lett opp smaken av det den tilberedes med.",
    descriptionEn: "Mild flavor, readily takes on the taste of whatever it's cooked with.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 3,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-fennikel",
    seasonId: "season-sensommer",
    slug: "fennikel",
    nameNo: "Fennikel",
    nameEn: "Fennel",
    aliases: ["fennikel"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 8,
    availableEndMonth: 10,
    seasonStartMonth: 8,
    seasonEndMonth: 10,
    peakStartMonth: 9,
    peakEndMonth: 9,
    descriptionNo: "Anisaktig smak, brukes både rå i salat og stekt eller braisert.",
    descriptionEn: "Anise-like flavor, used both raw in salads and roasted or braised.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 4,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-gulrot",
    seasonId: "season-sensommer",
    slug: "gulrot",
    nameNo: "Gulrot",
    nameEn: "Carrots",
    aliases: ["gulrot", "gulrøtter"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 1,
    availableEndMonth: 12,
    seasonStartMonth: 7,
    seasonEndMonth: 2,
    peakStartMonth: 8,
    peakEndMonth: 9,
    descriptionNo: "Nygravde gulrøtter er søtest om sommeren og tidlig høst. Lagringsgulrøtter holder seg godt utover vinteren.",
    descriptionEn: "Freshly dug carrots are sweetest in summer and early autumn. Stored carrots keep well into winter.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 5,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-rodbeter",
    seasonId: "season-sensommer",
    slug: "rodbeter",
    nameNo: "Rødbeter",
    nameEn: "Beetroot",
    aliases: ["rødbete", "rødbeter"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 1,
    availableEndMonth: 12,
    seasonStartMonth: 7,
    seasonEndMonth: 2,
    peakStartMonth: 8,
    peakEndMonth: 9,
    descriptionNo: "Norske rødbeter lagres godt og er derfor tilgjengelige langt utover selve innhøstingen.",
    descriptionEn: "Norwegian beets store well and stay available long after the actual harvest.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 6,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-poteter",
    seasonId: "season-sensommer",
    slug: "poteter",
    nameNo: "Poteter",
    nameEn: "Potatoes",
    aliases: ["poteter", "lagringspoteter"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 1,
    availableEndMonth: 12,
    seasonStartMonth: 8,
    seasonEndMonth: 4,
    peakStartMonth: 9,
    peakEndMonth: 10,
    descriptionNo: "Lagringspoteter fra høsthøstingen holder seg godt gjennom vinteren og utover våren.",
    descriptionEn: "Stored potatoes from the autumn harvest keep well through winter and into spring.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 7,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-purre",
    seasonId: "season-sensommer",
    slug: "purre",
    nameNo: "Purre",
    nameEn: "Leek",
    aliases: ["purre", "purreløk"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 8,
    availableEndMonth: 3,
    seasonStartMonth: 8,
    seasonEndMonth: 3,
    peakStartMonth: 10,
    peakEndMonth: 12,
    descriptionNo: "Mildere enn løk, med en søtlig smak som forsterkes ved tilberedning.",
    descriptionEn: "Milder than onion, with a slightly sweet flavor that intensifies when cooked.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 8,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-lok",
    seasonId: "season-sensommer",
    slug: "lok",
    nameNo: "Løk",
    nameEn: "Onion",
    aliases: ["løk", "gul løk", "kepaløk"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 1,
    availableEndMonth: 12,
    seasonStartMonth: 8,
    seasonEndMonth: 3,
    peakStartMonth: 9,
    peakEndMonth: 10,
    descriptionNo: "Norsk løk lagres godt gjennom vinteren og er derfor tilgjengelig lenge etter innhøsting.",
    descriptionEn: "Norwegian onions store well through winter and stay available long after harvest.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 9,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-bjornebaer",
    seasonId: "season-sensommer",
    slug: "bjornebaer",
    nameNo: "Bjørnebær",
    nameEn: "Blackberries",
    aliases: ["bjørnebær"],
    category: "berry",
    originGroup: "skogen",
    origin: "norwegian",
    availableStartMonth: 8,
    availableEndMonth: 9,
    seasonStartMonth: 8,
    seasonEndMonth: 9,
    peakStartMonth: 8,
    peakEndMonth: 9,
    descriptionNo: "Ville bjørnebær finnes langs skogkanter og steingjerder utover sensommeren.",
    descriptionEn: "Wild blackberries grow along forest edges and stone walls through late summer.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 10,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-plommer",
    seasonId: "season-sensommer",
    slug: "plommer",
    nameNo: "Plommer",
    nameEn: "Plums",
    aliases: ["plomme", "plommer"],
    category: "fruit",
    originGroup: "hagen",
    origin: "norwegian",
    availableStartMonth: 8,
    availableEndMonth: 9,
    seasonStartMonth: 8,
    seasonEndMonth: 9,
    peakStartMonth: 8,
    peakEndMonth: 9,
    descriptionNo: "Norske plommer varierer fra syrlige til søte avhengig av sort og modningsgrad.",
    descriptionEn: "Norwegian plums range from tart to sweet depending on variety and ripeness.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 11,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-multer",
    seasonId: "season-sensommer",
    slug: "multer",
    nameNo: "Multer",
    nameEn: "Cloudberries",
    aliases: ["multer", "molter"],
    category: "berry",
    originGroup: "skogen",
    origin: "norwegian",
    availableStartMonth: 7,
    availableEndMonth: 8,
    seasonStartMonth: 7,
    seasonEndMonth: 8,
    peakStartMonth: 8,
    peakEndMonth: 8,
    descriptionNo: "Kort, væravhengig sesong, hovedsakelig i Nord-Norge og på fjellet.",
    descriptionEn: "A short, weather-dependent season, mainly in northern Norway and in the mountains.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 12,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-kantareller",
    seasonId: "season-sensommer",
    slug: "kantarell",
    nameNo: "Kantarell",
    nameEn: "Chanterelle",
    aliases: ["kantarell", "kantareller"],
    category: "mushroom",
    originGroup: "skogen",
    origin: "norwegian",
    availableStartMonth: 7,
    availableEndMonth: 10,
    seasonStartMonth: 7,
    seasonEndMonth: 10,
    peakStartMonth: 8,
    peakEndMonth: 9,
    descriptionNo: "Kommer normalt fra midt- eller sensommeren og fortsetter utover høsten.",
    descriptionEn: "Normally arrives from mid or late summer and continues into autumn.",
    seasonNoteNo:
      "Kantarellen kommer vanligvis fra midt- eller sensommeren og fortsetter utover høsten, avhengig av nedbør og temperatur. Ingen fast startdato kan settes.",
    seasonNoteEn:
      "Chanterelles usually arrive from mid or late summer and continue into autumn, depending on rainfall and temperature. No fixed start date can be set.",
    sourceName: SOPPFORBUND,
    sourceUrl: null,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 13,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-steinsopp",
    seasonId: "season-sensommer",
    slug: "steinsopp",
    nameNo: "Steinsopp",
    nameEn: "Porcini",
    aliases: ["steinsopp", "steinsoppen"],
    category: "mushroom",
    originGroup: "skogen",
    origin: "norwegian",
    availableStartMonth: 8,
    availableEndMonth: 10,
    seasonStartMonth: 8,
    seasonEndMonth: 10,
    peakStartMonth: 8,
    peakEndMonth: 8,
    descriptionNo: "Finnes normalt fra august til oktober, med en tendens til å være mest tilgjengelig i august.",
    descriptionEn: "Normally found from August to October, tending to be most available in August.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: SOPPFORBUND,
    sourceUrl: null,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 14,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-piggsopp",
    seasonId: "season-sensommer",
    slug: "piggsopp",
    nameNo: "Piggsopp",
    nameEn: "Hedgehog mushroom",
    aliases: ["piggsopp"],
    category: "mushroom",
    originGroup: "skogen",
    origin: "norwegian",
    availableStartMonth: 8,
    availableEndMonth: 10,
    seasonStartMonth: 8,
    seasonEndMonth: 10,
    peakStartMonth: 9,
    peakEndMonth: 9,
    descriptionNo: "Mild smak og fast konsistens, forveksles sjelden med giftige sopper.",
    descriptionEn: "Mild flavor and firm texture, rarely confused with poisonous mushrooms.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: SOPPFORBUND,
    sourceUrl: null,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 15,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-kreps",
    seasonId: "season-sensommer",
    slug: "kreps",
    nameNo: "Kreps",
    nameEn: "Crayfish",
    aliases: ["kreps", "ferskvannskreps"],
    category: "shellfish",
    originGroup: "havet",
    origin: "norwegian",
    availableStartMonth: 8,
    availableEndMonth: 8,
    seasonStartMonth: 8,
    seasonEndMonth: 8,
    peakStartMonth: 8,
    peakEndMonth: 8,
    descriptionNo: "Kort, tradisjonsrik sesong i august.",
    descriptionEn: "A short, tradition-rich season in August.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FISKERIDIR,
    sourceUrl: null,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 16,
    createdAt: TS,
    updatedAt: TS,
  },

  // ══════════════════════════ HØST (spesifikasjonens punkt 13) ══════════════════════════
  {
    id: "ingr-hummer",
    seasonId: "season-host",
    slug: "hummer",
    nameNo: "Hummer",
    nameEn: "Lobster",
    aliases: ["hummer", "norsk hummer"],
    category: "shellfish",
    originGroup: "havet",
    origin: "norwegian",
    availableStartMonth: 10,
    availableEndMonth: 3,
    seasonStartMonth: 10,
    seasonEndMonth: 3,
    peakStartMonth: 10,
    peakEndMonth: 11,
    descriptionNo: "Norsk hummerfiske åpner 1. oktober og varer til slutten av mars.",
    descriptionEn: "Norwegian lobster fishing opens on October 1st and runs until the end of March.",
    seasonNoteNo:
      "Norsk hummerfiske åpner 1. oktober og varer til slutten av mars. Hummer hører derfor naturlig hjemme blant høstens og vinterens sjømatråvarer, ikke sommeren.",
    seasonNoteEn:
      "Norwegian lobster fishing opens on October 1st and runs until the end of March. Lobster therefore naturally belongs among autumn and winter's seafood, not summer.",
    sourceName: FISKERIDIR,
    sourceUrl: "https://meny.no/om-skalldyr/skalldyr-sesong-vinter",
    sourceNote: "Hummerfisket er strengt regulert, med fastsatt åpningsdato 1. oktober.",
    verifiedAt: VERIFIED,
    sortOrder: 1,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-krabbe",
    seasonId: "season-host",
    slug: "krabbe",
    nameNo: "Krabbe",
    nameEn: "Crab",
    aliases: ["krabbe", "taskekrabbe"],
    category: "shellfish",
    originGroup: "havet",
    origin: "norwegian",
    availableStartMonth: 7,
    availableEndMonth: 12,
    seasonStartMonth: 9,
    seasonEndMonth: 11,
    peakStartMonth: 9,
    peakEndMonth: 10,
    descriptionNo:
      "Tilgjengelig store deler av året, men sesongen strekker seg fra september til november, og Norges sjømatråd trekker spesielt fram september og oktober.",
    descriptionEn:
      "Available for much of the year, but the season runs from September to November, with the Norwegian Seafood Council particularly highlighting September and October.",
    seasonNoteNo:
      "Norsk krabbe er tilgjengelig store deler av året, men sesongen strekker seg fra september til november. Norges sjømatråd trekker spesielt fram september og oktober som når den er på sitt beste.",
    seasonNoteEn:
      "Norwegian crab is available much of the year, but the season runs from September to November. The Norwegian Seafood Council particularly highlights September and October as when it's at its best.",
    sourceName: GODFISK,
    sourceUrl: null,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 2,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-sjokreps",
    seasonId: "season-host",
    slug: "sjokreps",
    nameNo: "Sjøkreps",
    nameEn: "Norway lobster",
    aliases: ["sjøkreps", "langustine"],
    category: "shellfish",
    originGroup: "havet",
    origin: "norwegian",
    availableStartMonth: 1,
    availableEndMonth: 12,
    seasonStartMonth: 9,
    seasonEndMonth: 11,
    peakStartMonth: 9,
    peakEndMonth: 10,
    descriptionNo: "Søtere og mer delikat enn vanlig reke, med tydelig eget kjøtt fra halen.",
    descriptionEn: "Sweeter and more delicate than common shrimp, with distinct meat from the tail.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: GODFISK,
    sourceUrl: null,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 3,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-blaskjell",
    seasonId: "season-host",
    slug: "blaskjell",
    nameNo: "Blåskjell",
    nameEn: "Blue mussels",
    aliases: ["blåskjell", "blåskjellene"],
    category: "shellfish",
    originGroup: "havet",
    origin: "norwegian",
    availableStartMonth: 9,
    availableEndMonth: 4,
    seasonStartMonth: 9,
    seasonEndMonth: 4,
    peakStartMonth: 11,
    peakEndMonth: 2,
    descriptionNo: "Kan i praksis skaffes store deler av året, men er tradisjonelt best i de kaldere månedene.",
    descriptionEn: "Can in practice be obtained much of the year, but is traditionally best in the colder months.",
    seasonNoteNo:
      "Blåskjell kan i praksis skaffes store deler av året, men er tradisjonelt tryggest og mest smakfulle i de kaldere månedene. Høst og vinter regnes som den beste perioden, ikke sommeren.",
    seasonNoteEn:
      "Blue mussels can in practice be obtained much of the year, but are traditionally safest and tastiest in the colder months. Autumn and winter are considered the best period, not summer.",
    sourceName: GODFISK,
    sourceUrl: null,
    sourceNote: "Følger den tradisjonelle tommelfingerregelen om måneder med bokstaven r.",
    verifiedAt: VERIFIED,
    sortOrder: 4,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-lam",
    seasonId: "season-host",
    slug: "lam",
    nameNo: "Lam",
    nameEn: "Lamb",
    aliases: ["lam", "norsk lam", "fersk lam"],
    category: "meat",
    originGroup: "beite",
    origin: "norwegian",
    availableStartMonth: 8,
    availableEndMonth: 11,
    seasonStartMonth: 8,
    seasonEndMonth: 11,
    peakStartMonth: 9,
    peakEndMonth: 10,
    descriptionNo: "Ferskt norsk lam kommer fra sensommeren, med hovedsesong særlig i september og oktober.",
    descriptionEn: "Fresh Norwegian lamb comes from late summer, with its main season especially in September and October.",
    seasonNoteNo:
      "Ferskt norsk lam kommer fra sensommeren, med hovedsesong særlig i september og oktober, når lammene har beitet gjennom sommeren.",
    seasonNoteEn:
      "Fresh Norwegian lamb comes from late summer, with its main season especially in September and October, once the lambs have grazed through summer.",
    sourceName: MATPRAT,
    sourceUrl: null,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 5,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-hjort",
    seasonId: "season-host",
    slug: "hjort",
    nameNo: "Hjort",
    nameEn: "Deer",
    aliases: ["hjort", "hjortekjøtt"],
    category: "game",
    originGroup: "beite",
    origin: "norwegian",
    availableStartMonth: 9,
    availableEndMonth: 12,
    seasonStartMonth: 9,
    seasonEndMonth: 12,
    peakStartMonth: 10,
    peakEndMonth: 11,
    descriptionNo: "Mørt, magert vilt med en mildere smak sammenlignet med annet storvilt.",
    descriptionEn: "Tender, lean game with a milder flavor compared to other big game.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: JAKT,
    sourceUrl: null,
    sourceNote: "Jakttidene varierer noe mellom regioner og forvaltningsområder.",
    verifiedAt: VERIFIED,
    sortOrder: 6,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-elg",
    seasonId: "season-host",
    slug: "elg",
    nameNo: "Elg",
    nameEn: "Moose",
    aliases: ["elg", "elgkjøtt"],
    category: "game",
    originGroup: "beite",
    origin: "norwegian",
    availableStartMonth: 9,
    availableEndMonth: 12,
    seasonStartMonth: 9,
    seasonEndMonth: 12,
    peakStartMonth: 10,
    peakEndMonth: 11,
    descriptionNo: "Norges mest jaktede storvilt, med magert og smakfullt kjøtt.",
    descriptionEn: "Norway's most hunted big game, with lean, flavorful meat.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: JAKT,
    sourceUrl: null,
    sourceNote: "Jakttidene varierer noe mellom regioner og forvaltningsområder.",
    verifiedAt: VERIFIED,
    sortOrder: 7,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-reinsdyr",
    // Hjemme-sesong rettet 28.08.2026: sto opprinnelig som "season-host"
    // (Høst, måneder okt-nov), men reinsdyrjakta går faktisk august-september
    // (se availableStartMonth/seasonStartMonth/peakStartMonth under) – et
    // vindu som IKKE overlapper Høst i det hele tatt. Det gjorde at
    // reinsdyr aldri kunne vise riktig status på sin egen hjemmeside (alltid
    // "utenfor sesong", uansett dato). Sensommer (aug-sep) er både riktig
    // jaktsesong OG overlapper korrekt.
    seasonId: "season-sensommer",
    slug: "reinsdyr",
    nameNo: "Reinsdyr",
    nameEn: "Reindeer",
    aliases: ["reinsdyr", "reinsdyrkjøtt", "rein"],
    category: "game",
    originGroup: "beite",
    origin: "norwegian",
    availableStartMonth: 8,
    availableEndMonth: 9,
    seasonStartMonth: 8,
    seasonEndMonth: 9,
    peakStartMonth: 8,
    peakEndMonth: 9,
    descriptionNo: "Vilt med en karakteristisk smak, tradisjonelt forbundet med Nord-Norge.",
    descriptionEn: "Game with a distinctive flavor, traditionally associated with Northern Norway.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: JAKT,
    sourceUrl: null,
    sourceNote: "Gjelder villreinjakt, kortere sesong enn øvrig storvilt. Jakttidene varierer mellom regioner.",
    verifiedAt: VERIFIED,
    sortOrder: 8,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-radyr",
    seasonId: "season-host",
    slug: "radyr",
    nameNo: "Rådyr",
    nameEn: "Roe deer",
    aliases: ["rådyr", "rådyrkjøtt"],
    category: "game",
    originGroup: "beite",
    origin: "norwegian",
    availableStartMonth: 8,
    availableEndMonth: 12,
    seasonStartMonth: 8,
    seasonEndMonth: 12,
    peakStartMonth: 9,
    peakEndMonth: 10,
    descriptionNo: "Det minste av de norske hjorteviltartene, med mørt og mildt kjøtt.",
    descriptionEn: "The smallest of Norway's deer species, with tender, mild meat.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: JAKT,
    sourceUrl: null,
    sourceNote: "Jakttidene varierer noe mellom regioner og forvaltningsområder.",
    verifiedAt: VERIFIED,
    sortOrder: 9,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-rype",
    seasonId: "season-host",
    slug: "rype",
    nameNo: "Rype",
    nameEn: "Ptarmigan",
    aliases: ["rype", "ryper"],
    category: "game",
    originGroup: "beite",
    origin: "norwegian",
    availableStartMonth: 9,
    availableEndMonth: 12,
    seasonStartMonth: 9,
    seasonEndMonth: 12,
    peakStartMonth: 10,
    peakEndMonth: 11,
    descriptionNo: "Liten viltfugl fra fjellet, med mørkt, viltsmakende kjøtt.",
    descriptionEn: "A small mountain game bird, with dark, gamey meat.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: JAKT,
    sourceUrl: null,
    sourceNote: "Jakttidene varierer noe mellom regioner og forvaltningsområder.",
    verifiedAt: VERIFIED,
    sortOrder: 10,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-skogsfugl",
    seasonId: "season-host",
    slug: "skogsfugl",
    nameNo: "Skogsfugl",
    nameEn: "Forest grouse",
    aliases: ["skogsfugl", "storfugl", "orrfugl"],
    category: "game",
    originGroup: "beite",
    origin: "norwegian",
    availableStartMonth: 9,
    availableEndMonth: 12,
    seasonStartMonth: 9,
    seasonEndMonth: 12,
    peakStartMonth: 10,
    peakEndMonth: 11,
    descriptionNo: "Viltfugl fra skogen, gjerne servert hel eller i gryte.",
    descriptionEn: "A forest game bird, often served whole or in a stew.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: JAKT,
    sourceUrl: null,
    sourceNote: "Jakttidene varierer noe mellom regioner og forvaltningsområder.",
    verifiedAt: VERIFIED,
    sortOrder: 11,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-traktkantarell",
    seasonId: "season-host",
    slug: "traktkantarell",
    nameNo: "Traktkantarell",
    nameEn: "Yellowfoot chanterelle",
    aliases: ["traktkantarell"],
    category: "mushroom",
    originGroup: "skogen",
    origin: "norwegian",
    availableStartMonth: 9,
    availableEndMonth: 11,
    seasonStartMonth: 9,
    seasonEndMonth: 11,
    peakStartMonth: 9,
    peakEndMonth: 10,
    descriptionNo: "Slank, traktformet sopp med kraftigere smak enn vanlig kantarell.",
    descriptionEn: "A slender, funnel-shaped mushroom with a stronger flavor than common chanterelles.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: SOPPFORBUND,
    sourceUrl: null,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 12,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-gresskar",
    seasonId: "season-host",
    slug: "gresskar",
    nameNo: "Gresskar",
    nameEn: "Pumpkin",
    aliases: ["gresskar", "squash gresskar"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 9,
    availableEndMonth: 11,
    seasonStartMonth: 9,
    seasonEndMonth: 11,
    peakStartMonth: 10,
    peakEndMonth: 10,
    descriptionNo: "Norske gresskar høstes om høsten og lagres godt utover vinteren.",
    descriptionEn: "Norwegian pumpkins are harvested in autumn and store well through winter.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 13,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-rodkal",
    seasonId: "season-host",
    slug: "rodkal",
    nameNo: "Rødkål",
    nameEn: "Red cabbage",
    aliases: ["rødkål"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 9,
    availableEndMonth: 3,
    seasonStartMonth: 9,
    seasonEndMonth: 3,
    peakStartMonth: 10,
    peakEndMonth: 11,
    descriptionNo: "Fast og lagringsdyktig, en klassiker til høst- og vintermiddager.",
    descriptionEn: "Firm and good for storing, a classic side for autumn and winter dinners.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 14,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-hvitkal",
    seasonId: "season-host",
    slug: "hvitkal",
    nameNo: "Hvitkål",
    nameEn: "White cabbage",
    aliases: ["hvitkål"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 9,
    availableEndMonth: 3,
    seasonStartMonth: 9,
    seasonEndMonth: 3,
    peakStartMonth: 10,
    peakEndMonth: 11,
    descriptionNo: "Fast og lagringsdyktig, brukes både rå, kokt og syrnet.",
    descriptionEn: "Firm and good for storing, used raw, cooked, and fermented.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 15,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-savoykal",
    seasonId: "season-host",
    slug: "savoykal",
    nameNo: "Savoykål",
    nameEn: "Savoy cabbage",
    aliases: ["savoykål"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 9,
    availableEndMonth: 12,
    seasonStartMonth: 9,
    seasonEndMonth: 12,
    peakStartMonth: 10,
    peakEndMonth: 11,
    descriptionNo: "Mildere og mer mørt enn vanlig hvitkål, med karakteristiske krusete blader.",
    descriptionEn: "Milder and more tender than white cabbage, with distinctive crinkled leaves.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 16,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-rosenkal",
    seasonId: "season-host",
    slug: "rosenkal",
    nameNo: "Rosenkål",
    nameEn: "Brussels sprouts",
    aliases: ["rosenkål"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 9,
    availableEndMonth: 2,
    seasonStartMonth: 9,
    seasonEndMonth: 2,
    peakStartMonth: 10,
    peakEndMonth: 12,
    descriptionNo: "Smaker mildere og søtere etter de første frostnettene.",
    descriptionEn: "Tastes milder and sweeter after the first frosty nights.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 17,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-jordskokk",
    seasonId: "season-host",
    slug: "jordskokk",
    nameNo: "Jordskokk",
    nameEn: "Jerusalem artichoke",
    aliases: ["jordskokk"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 10,
    availableEndMonth: 3,
    seasonStartMonth: 10,
    seasonEndMonth: 3,
    peakStartMonth: 11,
    peakEndMonth: 12,
    descriptionNo: "Nøtteaktig smak, i slekt med solsikke snarere enn potet.",
    descriptionEn: "A nutty flavor, related to the sunflower rather than the potato.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 18,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-sellerirot",
    seasonId: "season-host",
    slug: "sellerirot",
    nameNo: "Sellerirot",
    nameEn: "Celeriac",
    aliases: ["sellerirot", "knollselleri"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 9,
    availableEndMonth: 3,
    seasonStartMonth: 9,
    seasonEndMonth: 3,
    peakStartMonth: 10,
    peakEndMonth: 12,
    descriptionNo: "Lagringsdyktig rotgrønnsak med en mild sellerismak.",
    descriptionEn: "A storage-friendly root vegetable with a mild celery flavor.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 19,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-pastinakk",
    seasonId: "season-host",
    slug: "pastinakk",
    nameNo: "Pastinakk",
    nameEn: "Parsnip",
    aliases: ["pastinakk"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 9,
    availableEndMonth: 3,
    seasonStartMonth: 9,
    seasonEndMonth: 3,
    peakStartMonth: 10,
    peakEndMonth: 12,
    descriptionNo: "Søtere enn gulrot, spesielt etter de første frostnettene.",
    descriptionEn: "Sweeter than carrot, especially after the first frosty nights.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 20,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-kalrot",
    seasonId: "season-host",
    slug: "kalrot",
    nameNo: "Kålrot",
    nameEn: "Swede",
    aliases: ["kålrot", "kålrabi"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 9,
    availableEndMonth: 4,
    seasonStartMonth: 9,
    seasonEndMonth: 4,
    peakStartMonth: 10,
    peakEndMonth: 12,
    descriptionNo: "Holder seg godt utover vinteren og våren.",
    descriptionEn: "Keeps well into winter and spring.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 21,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-epler",
    seasonId: "season-host",
    slug: "epler",
    nameNo: "Epler",
    nameEn: "Apples",
    aliases: ["eple", "epler", "norske epler"],
    category: "fruit",
    originGroup: "hagen",
    origin: "norwegian",
    availableStartMonth: 8,
    availableEndMonth: 11,
    seasonStartMonth: 8,
    seasonEndMonth: 11,
    peakStartMonth: 9,
    peakEndMonth: 10,
    descriptionNo: "Norske epler kommer i mange sorter, fra syrlige til søte, og lagres ofte godt utover vinteren.",
    descriptionEn: "Norwegian apples come in many varieties, from tart to sweet, and often store well into winter.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 22,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-paerer",
    seasonId: "season-host",
    slug: "paerer",
    nameNo: "Pærer",
    nameEn: "Pears",
    aliases: ["pære", "pærer"],
    category: "fruit",
    originGroup: "hagen",
    origin: "norwegian",
    availableStartMonth: 8,
    availableEndMonth: 11,
    seasonStartMonth: 8,
    seasonEndMonth: 11,
    peakStartMonth: 9,
    peakEndMonth: 10,
    descriptionNo: "Ettermodnes gjerne på kjøkkenbenken etter innhøsting.",
    descriptionEn: "Often ripened further on the kitchen counter after harvest.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 23,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-tyttebaer",
    seasonId: "season-host",
    slug: "tyttebaer",
    nameNo: "Tyttebær",
    nameEn: "Lingonberries",
    aliases: ["tyttebær"],
    category: "berry",
    originGroup: "skogen",
    origin: "norwegian",
    availableStartMonth: 8,
    availableEndMonth: 10,
    seasonStartMonth: 8,
    seasonEndMonth: 10,
    peakStartMonth: 9,
    peakEndMonth: 9,
    descriptionNo: "Syrlige skogsbær, tradisjonelt brukt som tilbehør til kjøtt og vilt.",
    descriptionEn: "Tart forest berries, traditionally served as an accompaniment to meat and game.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 24,
    createdAt: TS,
    updatedAt: TS,
  },

  // ══════════════════════════ VINTER (spesifikasjonens punkt 14) ══════════════════════════
  {
    id: "ingr-gronnkal",
    seasonId: "season-vinter",
    slug: "gronnkal",
    nameNo: "Grønnkål",
    nameEn: "Kale",
    aliases: ["grønnkål", "kale"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 10,
    availableEndMonth: 3,
    seasonStartMonth: 10,
    seasonEndMonth: 3,
    peakStartMonth: 11,
    peakEndMonth: 2,
    descriptionNo: "Blir søtere av den første frosten.",
    descriptionEn: "Sweetened by the first frost.",
    seasonNoteNo:
      "Grønnkål tåler frost godt, og smaken regnes gjerne som bedre etter de første frostnettene om høsten og vinteren.",
    seasonNoteEn:
      "Kale tolerates frost well, and its flavour is generally considered better after the first frosty nights of autumn and winter.",
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 1,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-persillerot",
    seasonId: "season-vinter",
    slug: "persillerot",
    nameNo: "Persillerot",
    nameEn: "Parsley root",
    aliases: ["persillerot"],
    category: "vegetable",
    originGroup: "jorda",
    origin: "norwegian",
    availableStartMonth: 10,
    availableEndMonth: 3,
    seasonStartMonth: 10,
    seasonEndMonth: 3,
    peakStartMonth: 11,
    peakEndMonth: 12,
    descriptionNo: "Rotgrønnsak i slekt med persille, med en mild, aromatisk smak.",
    descriptionEn: "A root vegetable related to parsley, with a mild, aromatic flavor.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 2,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-reker",
    seasonId: "season-vinter",
    slug: "reker",
    nameNo: "Reker",
    nameEn: "Prawns",
    aliases: ["reker", "kokte reker"],
    category: "shellfish",
    originGroup: "havet",
    origin: "norwegian",
    availableStartMonth: 1,
    availableEndMonth: 12,
    seasonStartMonth: 10,
    seasonEndMonth: 3,
    peakStartMonth: 12,
    peakEndMonth: 2,
    descriptionNo: "Fiskes hele året, men fremheves gjerne som en vinterråvare.",
    descriptionEn: "Fished year-round, but often highlighted as a winter ingredient.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: GODFISK,
    sourceUrl: null,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 3,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-torsk",
    seasonId: "season-vinter",
    slug: "torsk",
    nameNo: "Torsk",
    nameEn: "Cod",
    aliases: ["torsk", "vanlig torsk"],
    category: "fish",
    originGroup: "havet",
    origin: "norwegian",
    availableStartMonth: 1,
    availableEndMonth: 12,
    seasonStartMonth: 12,
    seasonEndMonth: 4,
    peakStartMonth: 2,
    peakEndMonth: 3,
    descriptionNo: "Vanlig helårstorsk, ikke å forveksle med skrei, som har en atskilt og mer avgrenset sesong.",
    descriptionEn: "Regular year-round cod, not to be confused with skrei, which has a separate and more limited season.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: GODFISK,
    sourceUrl: null,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 4,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-klementiner",
    seasonId: "season-vinter",
    slug: "klementin",
    nameNo: "Klementiner",
    nameEn: "Clementines",
    aliases: ["klementin", "klementiner", "mandarin"],
    category: "fruit",
    originGroup: "jorda",
    origin: "imported",
    availableStartMonth: 11,
    availableEndMonth: 1,
    seasonStartMonth: 11,
    seasonEndMonth: 1,
    peakStartMonth: 12,
    peakEndMonth: 12,
    descriptionNo: "Importert vintersesongvare, ikke en norsk råvare.",
    descriptionEn: "An imported winter-season fruit, not a Norwegian ingredient.",
    seasonNoteNo:
      "Klementiner er en importert vintersesongvare, ikke en norsk råvare. De regnes likevel som en klassisk del av den norske julesesongen.",
    seasonNoteEn:
      "Clementines are an imported winter-season fruit, not a Norwegian ingredient. They are nonetheless considered a classic part of the Norwegian Christmas season.",
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 5,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-appelsin",
    seasonId: "season-vinter",
    slug: "appelsin",
    nameNo: "Appelsin",
    nameEn: "Orange",
    aliases: ["appelsin", "appelsiner"],
    category: "fruit",
    originGroup: "jorda",
    origin: "imported",
    availableStartMonth: 11,
    availableEndMonth: 3,
    seasonStartMonth: 11,
    seasonEndMonth: 3,
    peakStartMonth: 12,
    peakEndMonth: 2,
    descriptionNo: "Importert vintersitrus, ikke norsk.",
    descriptionEn: "Imported winter citrus, not Norwegian.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 6,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-blodappelsin",
    seasonId: "season-vinter",
    slug: "blodappelsin",
    nameNo: "Blodappelsin",
    nameEn: "Blood orange",
    aliases: ["blodappelsin", "blodappelsiner"],
    category: "fruit",
    originGroup: "jorda",
    origin: "imported",
    availableStartMonth: 12,
    availableEndMonth: 3,
    seasonStartMonth: 12,
    seasonEndMonth: 3,
    peakStartMonth: 1,
    peakEndMonth: 2,
    descriptionNo: "En svært relevant vinterråvare kulinarisk, men importert, ikke norsk.",
    descriptionEn: "A very relevant winter ingredient culinarily, but imported, not Norwegian.",
    seasonNoteNo:
      "Blodappelsin er en importert vinterråvare med kort sesong, typisk fra desember til mars. Den er ikke norsk, selv om den er svært relevant kulinarisk om vinteren.",
    seasonNoteEn:
      "Blood orange is an imported winter ingredient with a short season, typically from December to March. It is not Norwegian, even though it is very relevant culinarily in winter.",
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 7,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-sitron",
    seasonId: "season-vinter",
    slug: "sitron",
    nameNo: "Sitron",
    nameEn: "Lemon",
    aliases: ["sitron", "sitroner"],
    category: "fruit",
    originGroup: "jorda",
    origin: "imported",
    availableStartMonth: 1,
    availableEndMonth: 12,
    seasonStartMonth: 11,
    seasonEndMonth: 3,
    peakStartMonth: 12,
    peakEndMonth: 2,
    descriptionNo: "Tilgjengelig hele året, men det italienske vinterutvalget fremheves gjerne fra november til mars.",
    descriptionEn: "Available year-round, but the Italian winter crop is often highlighted from November to March.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 8,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "ingr-grapefrukt",
    seasonId: "season-vinter",
    slug: "grapefrukt",
    nameNo: "Grapefrukt",
    nameEn: "Grapefruit",
    aliases: ["grapefrukt"],
    category: "fruit",
    originGroup: "jorda",
    origin: "imported",
    availableStartMonth: 12,
    availableEndMonth: 4,
    seasonStartMonth: 12,
    seasonEndMonth: 4,
    peakStartMonth: 1,
    peakEndMonth: 2,
    descriptionNo: "Importert vintersitrus, ikke norsk.",
    descriptionEn: "Imported winter citrus, not Norwegian.",
    seasonNoteNo: null,
    seasonNoteEn: null,
    sourceName: FRUKT,
    sourceUrl: FRUKT_URL,
    sourceNote: null,
    verifiedAt: VERIFIED,
    sortOrder: 9,
    createdAt: TS,
    updatedAt: TS,
  },
];

export function getDemoSeasonalIngredients(seasonId: string): SeasonalIngredient[] {
  return demoSeasonalIngredients.filter((i) => i.seasonId === seasonId).sort((a, b) => a.sortOrder - b.sortOrder);
}

/** Alle råvarer, uavhengig av hjemme-sesong – grunnlaget for søket
 * (spesifikasjonens punkt 26/27) og for råvaredetaljsiden, som må kunne slå
 * opp én råvare på slug uten å vite hvilken sesong den tilhører. Se
 * lib/data/seasons.ts sin getAllSeasonalIngredientsFlat() for
 * databaseekvivalenten. */
export function getAllDemoSeasonalIngredients(): SeasonalIngredient[] {
  return [...demoSeasonalIngredients].sort((a, b) => a.sortOrder - b.sortOrder);
}

export function findDemoSeasonalIngredient(slug: string): SeasonalIngredient | undefined {
  return demoSeasonalIngredients.find((i) => i.slug === slug);
}
