// AUTO-GENERERT (05.10.2026) fra shopping-list-purchase-normalization-spec.md v1.0.
// IKKE REDIGER MANUELT. Kilde: spesifikasjonens "Implementerbart aliasregister" (734
// rader, inkl. U1/U2) og "Komplett hovedtabell" (309 canonical råvarer). Generert
// mekanisk fra den verbatim-gjengitte spesifikasjonsteksten for å unngå
// transkripsjonsfeil i de 734 aliasene / 309 radene.
//
// MERK (rad 041, "paprika"): spesifikasjonens egen tabellcelle for denne ene
// raden er betinget tekst ("`paprika_powder` ved ts-form; ellers
// `pepper_fruit_unspecified`"), ikke en ren ID som alle de andre 733 radene.
// Default-grenen (`pepper_fruit_unspecified`/context_required) er lagt inn her;
// selve ts-formen-til-paprikapulver-presedensen (presedensregel 4) er
// implementert som egen kode i purchase-engine.ts, ikke som en alias-rad.

export interface PurchaseAlias {
  auditRow: string;
  name: string;
  id: string;
  form: string;
}

export const PURCHASE_ALIASES: PurchaseAlias[] = [
  { auditRow: '001', name: 'salt', id: 'salt', form: 'as_named' },
  { auditRow: '001', name: 'fint havsalt', id: 'salt_fine', form: 'as_named' },
  { auditRow: '001', name: 'flaksalt', id: 'salt_flake', form: 'as_named' },
  { auditRow: '001', name: 'fint salt', id: 'salt_fine', form: 'as_named' },
  { auditRow: '001', name: 'evt. litt salt', id: 'salt', form: 'as_named' },
  { auditRow: '001', name: 'en klype salt', id: 'salt', form: 'as_named' },
  { auditRow: '001', name: 'salt ved behov', id: 'salt', form: 'as_named' },
  { auditRow: '001', name: 'grovt havsalt', id: 'salt_coarse', form: 'as_named' },
  { auditRow: '002', name: 'sort pepper', id: 'pepper_black_ground', form: 'as_named' },
  { auditRow: '002', name: 'nykvernet sort pepper', id: 'pepper_black_ground', form: 'as_named' },
  { auditRow: '002', name: 'pepper', id: 'pepper_unspecified', form: 'as_named' },
  { auditRow: '002', name: 'hele sorte pepperkorn', id: 'pepper_black_whole', form: 'as_named' },
  { auditRow: '002', name: 'grovknuste sorte pepperkorn', id: 'pepper_black_crushed', form: 'as_named' },
  { auditRow: '002', name: 'litt nykvernet sort pepper', id: 'pepper_black_ground', form: 'as_named' },
  { auditRow: '002', name: 'hel sort pepper', id: 'pepper_black_whole', form: 'as_named' },
  { auditRow: '002', name: 'kvernet pepper', id: 'pepper_unspecified', form: 'as_named' },
  { auditRow: '002', name: 'hele pepperkorn', id: 'pepper_whole_unspecified', form: 'as_named' },
  { auditRow: '002', name: 'grovkvernet sort pepper', id: 'pepper_black_ground', form: 'as_named' },
  { auditRow: '003', name: 'hvitløksfedd', id: 'garlic', form: 'clove' },
  { auditRow: '003', name: 'fedd hvitløk', id: 'garlic', form: 'clove' },
  { auditRow: '003', name: 'hvitløk', id: 'garlic', form: 'context_required' },
  { auditRow: '003', name: 'hvitløkspulver', id: 'garlic_powder', form: 'as_named' },
  { auditRow: '003', name: 'lite fedd hvitløk', id: 'garlic', form: 'clove' },
  { auditRow: '003', name: 'lite hvitløksfedd', id: 'garlic', form: 'clove' },
  { auditRow: '003', name: 'presset hvitløksfedd', id: 'garlic', form: 'clove' },
  { auditRow: '003', name: 'pressede hvitløksfedd', id: 'garlic', form: 'clove' },
  { auditRow: '003', name: 'hvitløkskrydder', id: 'garlic_seasoning', form: 'as_named' },
  { auditRow: '004', name: 'sitron', id: 'lemon', form: 'context_required' },
  { auditRow: '004', name: 'saft av sitron', id: 'lemon', form: 'juice' },
  { auditRow: '004', name: 'sitronsaft', id: 'lemon', form: 'juice' },
  { auditRow: '004', name: 'fersk sitronsaft', id: 'lemon', form: 'juice' },
  { auditRow: '004', name: 'ferskpresset sitronsaft', id: 'lemon', form: 'juice' },
  { auditRow: '004', name: 'sitronskall', id: 'lemon', form: 'zest' },
  { auditRow: '004', name: 'sitronbåter', id: 'lemon', form: 'wedge' },
  { auditRow: '004', name: 'finrevet sitronskall', id: 'lemon', form: 'zest' },
  { auditRow: '004', name: 'sitronpepper', id: 'lemon_pepper', form: 'as_named' },
  { auditRow: '004', name: 'sitronjuice', id: 'lemon', form: 'juice' },
  { auditRow: '004', name: 'sitronzest', id: 'lemon', form: 'zest' },
  { auditRow: '004', name: 'finrevet skall av 1 sitron', id: 'lemon', form: 'zest_fruit_count:1' },
  { auditRow: '005', name: 'smør', id: 'butter', form: 'as_named' },
  { auditRow: '005', name: 'kaldt smør', id: 'butter', form: 'as_named' },
  { auditRow: '005', name: 'smeltet smør', id: 'butter', form: 'as_named' },
  { auditRow: '005', name: 'brunet smør', id: 'butter_browned', form: 'as_named' },
  { auditRow: '005', name: 'meierismør', id: 'butter', form: 'as_named' },
  { auditRow: '005', name: 'nøytral olje eller smør', id: 'choice_oil_butter', form: 'choice' },
  { auditRow: '005', name: 'smør, smeltet', id: 'butter', form: 'as_named' },
  { auditRow: '006', name: 'olivenolje', id: 'olive_oil', form: 'as_named' },
  { auditRow: '006', name: 'extra virgin olivenolje', id: 'olive_oil_extra_virgin', form: 'as_named' },
  { auditRow: '006', name: 'extra virgin olivolje', id: 'olive_oil_extra_virgin', form: 'as_named' },
  { auditRow: '006', name: 'litt olivenolje', id: 'olive_oil', form: 'as_named' },
  { auditRow: '007', name: 'nøytral olje', id: 'neutral_oil', form: 'as_named' },
  { auditRow: '007', name: 'olje', id: 'oil_unspecified', form: 'as_named' },
  { auditRow: '007', name: 'nøytral olje til steking', id: 'neutral_oil', form: 'as_named' },
  { auditRow: '007', name: 'nøytral olje til fritering', id: 'neutral_oil', form: 'as_named' },
  { auditRow: '008', name: 'gul løk', id: 'onion_yellow', form: 'as_named' },
  { auditRow: '008', name: 'liten gul løk', id: 'onion_yellow', form: 'as_named' },
  { auditRow: '008', name: 'stor gul løk', id: 'onion_yellow', form: 'as_named' },
  { auditRow: '008', name: 'gule løk', id: 'onion_yellow', form: 'as_named' },
  { auditRow: '008', name: 'løkpulver', id: 'onion_powder', form: 'as_named' },
  { auditRow: '008', name: 'løk', id: 'onion_unspecified', form: 'as_named' },
  { auditRow: '008', name: 'store gule løk', id: 'onion_yellow', form: 'as_named' },
  { auditRow: '008', name: 'crispy løk', id: 'onion_crispy', form: 'as_named' },
  { auditRow: '009', name: 'bladpersille', id: 'parsley_flat_fresh', form: 'as_named' },
  { auditRow: '009', name: 'frisk persille', id: 'parsley_fresh', form: 'as_named' },
  { auditRow: '009', name: 'persille', id: 'parsley_fresh', form: 'as_named' },
  { auditRow: '009', name: 'fersk persille', id: 'parsley_fresh', form: 'as_named' },
  { auditRow: '009', name: 'fersk bladpersille', id: 'parsley_flat_fresh', form: 'as_named' },
  { auditRow: '009', name: 'finhakket persille', id: 'parsley_fresh', form: 'chopped' },
  { auditRow: '009', name: 'flatbladet persille', id: 'parsley_flat_fresh', form: 'as_named' },
  { auditRow: '009', name: 'finhakket bladpersille', id: 'parsley_flat_fresh', form: 'chopped' },
  { auditRow: '009', name: 'fersk persille eller mynte', id: 'choice_parsley_mint', form: 'choice' },
  { auditRow: '009', name: 'frisk estragon eller persille', id: 'choice_tarragon_parsley', form: 'choice' },
  { auditRow: '009', name: 'grovhakket bladpersille', id: 'parsley_flat_fresh', form: 'chopped' },
  { auditRow: '010', name: 'småpoteter', id: 'potato_small', form: 'as_named' },
  { auditRow: '010', name: 'poteter', id: 'potato', form: 'as_named' },
  { auditRow: '010', name: 'melne poteter', id: 'potato_floury', form: 'as_named' },
  { auditRow: '010', name: 'faste poteter', id: 'potato_waxy', form: 'as_named' },
  { auditRow: '010', name: 'rå poteter', id: 'potato', form: 'as_named' },
  { auditRow: '010', name: 'kokte poteter', id: 'potato_cooked', form: 'as_named' },
  { auditRow: '011', name: 'kremfløte', id: 'r011', form: 'as_named' },
  { auditRow: '012', name: 'hvetemel', id: 'wheat_flour', form: 'as_named' },
  { auditRow: '012', name: 'byggmel', id: 'barley_flour', form: 'as_named' },
  { auditRow: '012', name: 'mel', id: 'flour_unspecified', form: 'as_named' },
  { auditRow: '013', name: 'vann', id: 'water', form: 'as_named' },
  { auditRow: '013', name: 'varmt vann', id: 'water', form: 'as_named' },
  { auditRow: '013', name: 'kaldt vann', id: 'water', form: 'as_named' },
  { auditRow: '013', name: 'boks tunfisk i vann', id: 'tuna_canned_water', form: 'container_count:boks' },
  { auditRow: '014', name: 'sukker', id: 'sugar_white', form: 'as_named' },
  { auditRow: '014', name: 'brunt sukker', id: 'sugar_brown', form: 'as_named' },
  { auditRow: '014', name: 'hvitt sukker', id: 'sugar_white', form: 'as_named' },
  { auditRow: '015', name: 'parmesan', id: 'parmesan', form: 'as_named' },
  { auditRow: '015', name: 'revet parmesan', id: 'parmesan', form: 'grated' },
  { auditRow: '015', name: 'finrevet parmesan', id: 'parmesan', form: 'grated' },
  { auditRow: '015', name: 'parmigiano reggiano', id: 'parmigiano_reggiano', form: 'as_named' },
  { auditRow: '016', name: 'egg', id: 'egg', form: 'whole' },
  { auditRow: '016', name: 'eggeplommer', id: 'egg', form: 'yolk' },
  { auditRow: '016', name: 'eggeplomme', id: 'egg', form: 'yolk' },
  { auditRow: '016', name: 'eggehviter', id: 'egg', form: 'white' },
  { auditRow: '016', name: 'helt egg', id: 'egg', form: 'whole' },
  { auditRow: '017', name: 'tomatpuré', id: 'tomato_paste', form: 'as_named' },
  { auditRow: '017', name: 'hakkede tomater', id: 'tomato_canned_chopped', form: 'as_named' },
  { auditRow: '017', name: 'hermetiske hele tomater', id: 'tomato_canned_whole', form: 'as_named' },
  { auditRow: '017', name: 'hermetiske tomater', id: 'tomato_canned_unspecified', form: 'as_named' },
  { auditRow: '017', name: 'passata', id: 'tomato_passata', form: 'as_named' },
  { auditRow: '017', name: 'hele flådde tomater', id: 'tomato_canned_whole', form: 'as_named' },
  { auditRow: '017', name: 'boks hakkede tomater', id: 'tomato_canned_chopped', form: 'container_count:boks' },
  { auditRow: '017', name: 'soltørkede tomater i olje', id: 'tomato_sundried_oil', form: 'as_named' },
  { auditRow: '017', name: 'olje fra de soltørkede tomatene', id: 'byproduct_tomato_oil', form: 'byproduct_not_purchased' },
  { auditRow: '017', name: 'hele, skrelte tomater på boks', id: 'tomato_canned_whole', form: 'as_named' },
  { auditRow: '017', name: 'boks hele flådde tomater', id: 'tomato_canned_whole', form: 'container_count:boks' },
  { auditRow: '017', name: 'hele, skrelte tomater', id: 'tomato_canned_whole', form: 'as_named' },
  { auditRow: '017', name: 'finhakka tomater', id: 'tomato_canned_finely_chopped', form: 'canned_finely_chopped' },
  { auditRow: '018', name: 'basmatiris', id: 'rice_basmati', form: 'as_named' },
  { auditRow: '018', name: 'jasminris', id: 'rice_jasmine', form: 'as_named' },
  { auditRow: '018', name: 'ris', id: 'rice_unspecified', form: 'as_named' },
  { auditRow: '018', name: 'langkornet ris', id: 'rice_longgrain', form: 'as_named' },
  { auditRow: '019', name: 'honning', id: 'r019', form: 'as_named' },
  { auditRow: '020', name: 'dijon-sennep', id: 'dijon', form: 'as_named' },
  { auditRow: '020', name: 'dijon', id: 'dijon', form: 'as_named' },
  { auditRow: '020', name: 'dijonsennep', id: 'dijon', form: 'as_named' },
  { auditRow: '021', name: 'chiliflak', id: 'chili_flakes', form: 'as_named' },
  { auditRow: '021', name: 'rød chili', id: 'chili_red_fresh', form: 'as_named' },
  { auditRow: '021', name: 'chilipulver', id: 'chili_powder', form: 'as_named' },
  { auditRow: '021', name: 'chilikrydder', id: 'chili_seasoning', form: 'as_named' },
  { auditRow: '021', name: 'pul biber eller aleppo-pepper', id: 'choice_pulbiber_aleppo', form: 'choice' },
  { auditRow: '021', name: 'tørkede røde chili', id: 'chili_red_dried', form: 'as_named' },
  { auditRow: '021', name: 'røde chili', id: 'chili_red_fresh', form: 'as_named' },
  { auditRow: '021', name: 'grønn chili', id: 'chili_green_fresh', form: 'as_named' },
  { auditRow: '021', name: 'chili', id: 'chili_unspecified', form: 'as_named' },
  { auditRow: '022', name: 'lime', id: 'lime', form: 'context_required' },
  { auditRow: '022', name: 'limesaft', id: 'lime', form: 'juice' },
  { auditRow: '022', name: 'limejuice', id: 'lime', form: 'juice' },
  { auditRow: '022', name: 'fersk limejuice', id: 'lime', form: 'juice' },
  { auditRow: '022', name: 'fersk limesaft', id: 'lime', form: 'juice' },
  { auditRow: '022', name: 'limeskall', id: 'lime', form: 'zest' },
  { auditRow: '022', name: 'tørkede persiske lime (limoo amani)', id: 'lime_persian_dried', form: 'as_named' },
  { auditRow: '022', name: 'ferskpresset limejuice', id: 'lime', form: 'juice' },
  { auditRow: '022', name: 'limebåter', id: 'lime', form: 'wedge' },
  { auditRow: '022', name: 'limezest', id: 'lime', form: 'zest' },
  { auditRow: '023', name: 'sjalottløk', id: 'r023', form: 'as_named' },
  { auditRow: '023', name: 'liten sjalottløk', id: 'r023', form: 'as_named' },
  { auditRow: '023', name: 'små sjalottløk', id: 'r023', form: 'as_named' },
  { auditRow: '024', name: 'paprikapulver', id: 'paprika_powder', form: 'as_named' },
  { auditRow: '024', name: 'røkt paprikapulver', id: 'paprika_smoked', form: 'as_named' },
  { auditRow: '024', name: 'røkt paprika', id: 'paprika_smoked', form: 'as_named' },
  { auditRow: '024', name: 'søtt ungarsk paprikapulver', id: 'paprika_sweet_hungarian', form: 'as_named' },
  { auditRow: '025', name: 'pasta', id: 'pasta_pasta', form: 'dry' },
  { auditRow: '025', name: 'spaghetti', id: 'pasta_spaghetti', form: 'dry' },
  { auditRow: '025', name: 'makaroni', id: 'pasta_makaroni', form: 'dry' },
  { auditRow: '025', name: 'linguine eller spaghetti', id: 'choice_pasta_linguine_spaghetti', form: 'choice' },
  { auditRow: '025', name: 'rigatoni eller penne', id: 'choice_pasta_rigatoni_penne', form: 'choice' },
  { auditRow: '025', name: 'rigatoni', id: 'pasta_rigatoni', form: 'dry' },
  { auditRow: '025', name: 'orzo', id: 'pasta_orzo', form: 'dry' },
  { auditRow: '025', name: 'lasagneplater', id: 'pasta_lasagne', form: 'dry' },
  { auditRow: '025', name: 'linguine', id: 'pasta_linguine', form: 'dry' },
  { auditRow: '025', name: 'tagliatelle', id: 'pasta_tagliatelle', form: 'dry' },
  { auditRow: '025', name: 'bucatini', id: 'pasta_bucatini', form: 'dry' },
  { auditRow: '025', name: 'linguine eller tagliatelle', id: 'choice_pasta_linguine_eller_tagliatelle', form: 'choice' },
  { auditRow: '025', name: 'lasagne-plater', id: 'pasta_lasagne', form: 'dry' },
  { auditRow: '025', name: 'penne eller rigatoni', id: 'choice_pasta_rigatoni_penne', form: 'choice' },
  { auditRow: '025', name: 'pappardelle', id: 'pasta_pappardelle', form: 'dry' },
  { auditRow: '025', name: 'spaghetti eller linguine', id: 'choice_pasta_linguine_spaghetti', form: 'choice' },
  { auditRow: '025', name: 'ditalini eller annen liten pasta', id: 'choice_pasta_ditalini_eller_annen_liten_pasta', form: 'choice' },
  { auditRow: '025', name: 'fettuccine', id: 'pasta_fettuccine', form: 'dry' },
  { auditRow: '025', name: 'penne eller fusilli', id: 'choice_pasta_penne_eller_fusilli', form: 'choice' },
  { auditRow: '025', name: 'trofie', id: 'pasta_trofie', form: 'dry' },
  { auditRow: '026', name: 'timian', id: 'thyme_unspecified', form: 'as_named' },
  { auditRow: '026', name: 'kvister timian', id: 'thyme_fresh', form: 'sprig' },
  { auditRow: '026', name: 'tørket timian', id: 'thyme_dried', form: 'as_named' },
  { auditRow: '026', name: 'frisk timian', id: 'thyme_fresh', form: 'as_named' },
  { auditRow: '026', name: 'kvist timian', id: 'thyme_fresh', form: 'sprig' },
  { auditRow: '026', name: 'fersk timian', id: 'thyme_fresh', form: 'as_named' },
  { auditRow: '026', name: 'finhakket timian', id: 'thyme_fresh', form: 'chopped' },
  { auditRow: '026', name: 'friske timianblader', id: 'thyme_fresh', form: 'leaf' },
  { auditRow: '026', name: 'kvister frisk timian', id: 'thyme_fresh', form: 'sprig' },
  { auditRow: '026', name: 'kvister fersk timian', id: 'thyme_fresh', form: 'sprig' },
  { auditRow: '027', name: 'tørket oregano', id: 'oregano_dried', form: 'as_named' },
  { auditRow: '027', name: 'oregano', id: 'oregano_unspecified', form: 'as_named' },
  { auditRow: '028', name: 'kyllingkraft', id: 'stock_chicken', form: 'as_named' },
  { auditRow: '028', name: 'kyllingkraft eller grønnsakskraft', id: 'choice_stock_chicken_vegetable', form: 'choice' },
  { auditRow: '028', name: 'kyllingbuljong', id: 'bouillon_chicken', form: 'as_named' },
  { auditRow: '028', name: 'kyllingbuljonpulver', id: 'bouillon_chicken_powder', form: 'as_named' },
  { auditRow: '028', name: 'terning kyllingbuljong', id: 'bouillon_chicken_cube', form: 'as_named' },
  { auditRow: '028', name: 'kraft fra kyllingen', id: 'byproduct_chicken_stock', form: 'byproduct_not_purchased' },
  { auditRow: '028', name: 'kyllingbuljongterning', id: 'bouillon_chicken_cube', form: 'as_named' },
  { auditRow: '028', name: 'varm kyllingkraft', id: 'stock_chicken', form: 'as_named' },
  { auditRow: '029', name: 'soyasaus', id: 'r029', form: 'as_named' },
  { auditRow: '030', name: 'rødløk', id: 'onion_red', form: 'as_named' },
  { auditRow: '030', name: 'liten rødløk', id: 'onion_red', form: 'as_named' },
  { auditRow: '030', name: 'finhakket rødløk', id: 'onion_red', form: 'chopped' },
  { auditRow: '030', name: 'syltet rødløk', id: 'onion_red_pickled', form: 'as_named' },
  { auditRow: '031', name: 'helmelk', id: 'milk_whole', form: 'as_named' },
  { auditRow: '031', name: 'melk', id: 'milk_unspecified', form: 'as_named' },
  { auditRow: '031', name: 'kulturmelk', id: 'milk_cultured', form: 'as_named' },
  { auditRow: '032', name: 'gulrøtter', id: 'r032', form: 'as_named' },
  { auditRow: '032', name: 'gulrot', id: 'r032', form: 'as_named' },
  { auditRow: '032', name: 'små gulrøtter', id: 'r032', form: 'as_named' },
  { auditRow: '032', name: 'liten gulrot', id: 'r032', form: 'as_named' },
  { auditRow: '032', name: 'kverna gulrot', id: 'r032', form: 'as_named' },
  { auditRow: '033', name: 'frisk koriander', id: 'coriander_fresh', form: 'as_named' },
  { auditRow: '033', name: 'koriander', id: 'coriander_fresh', form: 'as_named' },
  { auditRow: '033', name: 'fersk koriander', id: 'coriander_fresh', form: 'as_named' },
  { auditRow: '033', name: 'liten håndfull thai-basilikum eller koriander', id: 'choice_thaibasil_coriander', form: 'choice' },
  { auditRow: '034', name: 'pastavann', id: 'pasta_water', form: 'as_named' },
  { auditRow: '034', name: 'salt til pastavannet', id: 'salt', form: 'as_named' },
  { auditRow: '034', name: 'salt til kokevannet', id: 'salt', form: 'as_named' },
  { auditRow: '034', name: 'kokevann', id: 'cooking_water', form: 'as_named' },
  { auditRow: '034', name: 'kraft fra trekkingen', id: 'byproduct_poaching_stock', form: 'byproduct_not_purchased' },
  { auditRow: '034', name: 'pastavann ved behov', id: 'pasta_water', form: 'as_named' },
  { auditRow: '034', name: 'kraft fra kokingen', id: 'byproduct_cooking_stock', form: 'byproduct_not_purchased' },
  { auditRow: '035', name: 'vårløk', id: 'r035', form: 'as_named' },
  { auditRow: '035', name: 'grønnløk', id: 'r035', form: 'as_named' },
  { auditRow: '036', name: 'kylling lårfilet', id: 'chicken_thigh_fillet', form: 'as_named' },
  { auditRow: '036', name: 'kyllinglår med bein og skinn', id: 'chicken_thigh_bone_skin', form: 'as_named' },
  { auditRow: '036', name: 'kyllinglår', id: 'chicken_thigh', form: 'as_named' },
  { auditRow: '036', name: 'kylling lårfilet med skinn', id: 'chicken_thigh_fillet_skin', form: 'as_named' },
  { auditRow: '036', name: 'kyllinglårfilet', id: 'chicken_thigh_fillet', form: 'as_named' },
  { auditRow: '037', name: 'cherrytomater', id: 'tomato_cherry', form: 'as_named' },
  { auditRow: '037', name: 'tomater', id: 'tomato_fresh', form: 'as_named' },
  { auditRow: '037', name: 'tomat', id: 'tomato_fresh', form: 'as_named' },
  { auditRow: '037', name: 'cherrytomat', id: 'tomato_cherry', form: 'as_named' },
  { auditRow: '037', name: 'gode cherrytomater', id: 'tomato_cherry', form: 'as_named' },
  { auditRow: '037', name: 'stor tomat', id: 'tomato_fresh', form: 'as_named' },
  { auditRow: '038', name: 'agurk', id: 'r038', form: 'as_named' },
  { auditRow: '039', name: 'kjøttdeig', id: 'mince_unspecified', form: 'as_named' },
  { auditRow: '039', name: 'kjøttdeig av storfe', id: 'mince_beef', form: 'as_named' },
  { auditRow: '039', name: 'karbonadedeig', id: 'mince_beef_lean', form: 'as_named' },
  { auditRow: '040', name: 'majones', id: 'r040', form: 'as_named' },
  { auditRow: '041', name: 'rød paprika', id: 'pepper_red', form: 'as_named' },
  { auditRow: '041', name: 'paprika', id: 'pepper_fruit_unspecified', form: 'context_required' },
  { auditRow: '041', name: 'store paprika', id: 'pepper_fruit_unspecified', form: 'as_named' },
  { auditRow: '041', name: 'gul paprika', id: 'pepper_yellow', form: 'as_named' },
  { auditRow: '041', name: 'søt paprika', id: 'pepper_fruit_unspecified', form: 'as_named' },
  { auditRow: '041', name: 'røde paprika', id: 'pepper_red', form: 'as_named' },
  { auditRow: '041', name: 'grønn paprika', id: 'pepper_green', form: 'as_named' },
  { auditRow: '042', name: 'kyllingfilet', id: 'chicken_breast', form: 'as_named' },
  { auditRow: '042', name: 'kyllingbryst', id: 'chicken_breast', form: 'as_named' },
  { auditRow: '042', name: 'kylling', id: 'chicken_unspecified', form: 'as_named' },
  { auditRow: '042', name: 'kyllingfileter', id: 'chicken_breast', form: 'as_named' },
  { auditRow: '042', name: 'kyllingbryst med skinn', id: 'chicken_breast_skin', form: 'as_named' },
  { auditRow: '043', name: 'godt brød', id: 'bread_generic', form: 'as_named' },
  { auditRow: '043', name: 'skiver godt landbrød', id: 'bread_country', form: 'slice' },
  { auditRow: '043', name: 'lyst brød', id: 'bread_white', form: 'as_named' },
  { auditRow: '043', name: 'godt landbrød', id: 'bread_country', form: 'as_named' },
  { auditRow: '043', name: 'skiver godt toastbrød', id: 'bread_toast', form: 'slice' },
  { auditRow: '043', name: 'store skiver godt landbrød', id: 'bread_country', form: 'slice' },
  { auditRow: '043', name: 'tykke skiver godt landbrød', id: 'bread_country', form: 'slice' },
  { auditRow: '043', name: 'godt surdeigsbrød eller baguette', id: 'choice_bread_sourdough_baguette', form: 'choice' },
  { auditRow: '043', name: 'skiver god kokt eller røkt skinke', id: 'choice_ham_cooked_smoked', form: 'choice' },
  { auditRow: '043', name: 'skiver godt brød', id: 'bread_generic', form: 'slice' },
  { auditRow: '044', name: 'fersk ingefær', id: 'ginger_fresh', form: 'as_named' },
  { auditRow: '044', name: 'ingefær', id: 'ginger_unspecified', form: 'as_named' },
  { auditRow: '044', name: 'revet ingefær', id: 'ginger_fresh', form: 'grated' },
  { auditRow: '044', name: 'ingefærpulver', id: 'ginger_ground', form: 'as_named' },
  { auditRow: '044', name: 'malt ingefær', id: 'ginger_ground', form: 'as_named' },
  { auditRow: '044', name: 'frisk ingefær', id: 'ginger_fresh', form: 'as_named' },
  { auditRow: '045', name: 'panko', id: 'panko', form: 'as_named' },
  { auditRow: '045', name: 'brødsmuler', id: 'breadcrumbs', form: 'as_named' },
  { auditRow: '045', name: 'strøkavring/panko', id: 'choice_rusk_panko', form: 'choice' },
  { auditRow: '045', name: 'panko eller brødsmuler', id: 'choice_panko_breadcrumbs', form: 'choice' },
  { auditRow: '046', name: 'fersk basilikum', id: 'basil_fresh', form: 'as_named' },
  { auditRow: '046', name: 'basilikum', id: 'basil_unspecified', form: 'as_named' },
  { auditRow: '046', name: 'frisk basilikum', id: 'basil_fresh', form: 'as_named' },
  { auditRow: '046', name: 'håndfull thai-basilikum', id: 'basil_thai_fresh', form: 'handful' },
  { auditRow: '046', name: 'blader fersk basilikum', id: 'basil_fresh', form: 'leaf' },
  { auditRow: '046', name: 'tørket basilikum', id: 'basil_dried', form: 'as_named' },
  { auditRow: '046', name: 'holy basil eller thai-basilikum', id: 'choice_holy_thai_basil', form: 'choice' },
  { auditRow: '046', name: 'blader frisk basilikum', id: 'basil_fresh', form: 'leaf' },
  { auditRow: '047', name: 'malt spisskummen', id: 'cumin_ground', form: 'as_named' },
  { auditRow: '047', name: 'spisskummen', id: 'cumin_unspecified', form: 'as_named' },
  { auditRow: '048', name: 'riseddik', id: 'r048', form: 'as_named' },
  { auditRow: '049', name: 'sesamfrø', id: 'sesame_seed', form: 'as_named' },
  { auditRow: '049', name: 'ristede sesamfrø', id: 'sesame_seed_roasted', form: 'as_named' },
  { auditRow: '050', name: 'gresk yoghurt', id: 'yoghurt_greek', form: 'as_named' },
  { auditRow: '050', name: 'bær, gresk yoghurt og lønnesirup', id: 'review_berries_yoghurt_syrup', form: 'review' },
  { auditRow: '051', name: 'tørr hvitvin', id: 'r051', form: 'as_named' },
  { auditRow: '051', name: 'hvitvin', id: 'r051', form: 'as_named' },
  { auditRow: '052', name: 'aromasopp', id: 'mushroom_brown', form: 'as_named' },
  { auditRow: '052', name: 'aromasopp eller sjampinjong', id: 'choice_mushroom_brown_button', form: 'choice' },
  { auditRow: '052', name: 'sjampinjong', id: 'mushroom_button', form: 'as_named' },
  { auditRow: '052', name: 'mini sjampinjong', id: 'mushroom_button_mini', form: 'as_named' },
  { auditRow: '053', name: 'oksekraft', id: 'r053', form: 'as_named' },
  { auditRow: '054', name: 'rømme', id: 'sourcream', form: 'as_named' },
  { auditRow: '054', name: 'seterrømme', id: 'sourcream_seter', form: 'as_named' },
  { auditRow: '055', name: 'avokado', id: 'r055', form: 'as_named' },
  { auditRow: '055', name: 'modne avokadoer', id: 'r055', form: 'as_named' },
  { auditRow: '055', name: 'stor avokado', id: 'r055', form: 'as_named' },
  { auditRow: '056', name: 'bacon', id: 'r056', form: 'as_named' },
  { auditRow: '056', name: 'skiver bacon', id: 'r056', form: 'slice' },
  { auditRow: '057', name: 'burrata', id: 'burrata', form: 'as_named' },
  { auditRow: '057', name: 'fersk mozzarella', id: 'mozzarella_fresh', form: 'as_named' },
  { auditRow: '057', name: 'mozzarella', id: 'mozzarella_unspecified', form: 'as_named' },
  { auditRow: '057', name: 'revet mozzarella', id: 'mozzarella_grated', form: 'grated' },
  { auditRow: '058', name: 'små tortillas', id: 'tortilla_small_unspecified', form: 'as_named' },
  { auditRow: '058', name: 'små maistortillaer', id: 'tortilla_small_corn', form: 'as_named' },
  { auditRow: '058', name: 'små tortillaer', id: 'tortilla_small_unspecified', form: 'as_named' },
  { auditRow: '058', name: 'store hvetetortillaer', id: 'tortilla_large_wheat', form: 'as_named' },
  { auditRow: '058', name: 'tortillaer', id: 'tortilla_unspecified', form: 'as_named' },
  { auditRow: '058', name: 'store tortillaer', id: 'tortilla_large_unspecified', form: 'as_named' },
  { auditRow: '058', name: 'medium tortillas', id: 'tortilla_medium_unspecified', form: 'as_named' },
  { auditRow: '058', name: 'små hvetetortillas', id: 'tortilla_small_wheat', form: 'as_named' },
  { auditRow: '058', name: 'store hvetetortillas', id: 'tortilla_large_wheat', form: 'as_named' },
  { auditRow: '058', name: 'mellomstore tortillalefser', id: 'tortilla_medium_unspecified', form: 'as_named' },
  { auditRow: '058', name: 'små tortillalefser', id: 'tortilla_small_unspecified', form: 'as_named' },
  { auditRow: '058', name: 'store tortillalefser', id: 'tortilla_large_unspecified', form: 'as_named' },
  { auditRow: '058', name: 'tortillalefse', id: 'tortilla_unspecified', form: 'as_named' },
  { auditRow: '059', name: 'sesamolje', id: 'r059', form: 'as_named' },
  { auditRow: '060', name: 'worcestershiresaus', id: 'r060', form: 'as_named' },
  { auditRow: '061', name: 'laurbærblad', id: 'r061', form: 'as_named' },
  { auditRow: '062', name: 'gurkemeie', id: 'turmeric_unspecified', form: 'as_named' },
  { auditRow: '062', name: 'gurkemejepulver', id: 'turmeric_ground', form: 'as_named' },
  { auditRow: '062', name: 'malt gurkemeie', id: 'turmeric_ground', form: 'as_named' },
  { auditRow: '063', name: 'babyspinat', id: 'spinach_baby', form: 'as_named' },
  { auditRow: '063', name: 'fersk spinat', id: 'spinach_fresh', form: 'as_named' },
  { auditRow: '064', name: 'grønnsakskraft', id: 'stock_vegetable', form: 'as_named' },
  { auditRow: '064', name: 'grønnsaksbuljong', id: 'bouillon_vegetable', form: 'as_named' },
  { auditRow: '064', name: 'grønnsaks- eller kyllingkraft', id: 'choice_stock_chicken_vegetable', form: 'choice' },
  { auditRow: '065', name: 'feta', id: 'r065', form: 'as_named' },
  { auditRow: '065', name: 'fetaost', id: 'r065', form: 'as_named' },
  { auditRow: '066', name: 'laksefilet', id: 'salmon_fillet', form: 'as_named' },
  { auditRow: '066', name: 'laksefilet uten skinn', id: 'salmon_fillet_skinless', form: 'as_named' },
  { auditRow: '066', name: 'laksefilet med skinn', id: 'salmon_fillet_skin', form: 'as_named' },
  { auditRow: '066', name: 'laks', id: 'salmon_unspecified', form: 'as_named' },
  { auditRow: '067', name: 'rødvin', id: 'r067', form: 'as_named' },
  { auditRow: '067', name: 'tørr rødvin', id: 'r067', form: 'as_named' },
  { auditRow: '068', name: 'frosne erter', id: 'peas_green_frozen', form: 'as_named' },
  { auditRow: '068', name: 'frosne grønne erter', id: 'peas_green_frozen', form: 'as_named' },
  { auditRow: '068', name: 'gule splitterter', id: 'peas_yellow_split', form: 'as_named' },
  { auditRow: '069', name: 'skiver cheddar', id: 'r069', form: 'slice' },
  { auditRow: '069', name: 'cheddar', id: 'r069', form: 'as_named' },
  { auditRow: '069', name: 'revet cheddar', id: 'r069', form: 'grated' },
  { auditRow: '070', name: 'ruccola', id: 'r070', form: 'as_named' },
  { auditRow: '071', name: 'brioche burgerbrød', id: 'r071', form: 'as_named' },
  { auditRow: '072', name: 'torskefilet', id: 'cod_fillet', form: 'as_named' },
  { auditRow: '072', name: 'torskefilet eller annen fast hvit fisk', id: 'choice_cod_whitefish', form: 'choice' },
  { auditRow: '072', name: 'torskefilet eller torskeloin', id: 'choice_cod_loin', form: 'choice' },
  { auditRow: '072', name: 'torskefilet uten skinn', id: 'cod_fillet_skinless', form: 'as_named' },
  { auditRow: '073', name: 'malt muskat', id: 'nutmeg_ground', form: 'as_named' },
  { auditRow: '073', name: 'muskat', id: 'nutmeg_unspecified', form: 'as_named' },
  { auditRow: '073', name: 'litt revet muskatnøtt', id: 'nutmeg_grated', form: 'grated' },
  { auditRow: '074', name: 'frisk dill', id: 'dill_fresh', form: 'as_named' },
  { auditRow: '074', name: 'dill', id: 'dill_unspecified', form: 'as_named' },
  { auditRow: '074', name: 'fersk dill', id: 'dill_fresh', form: 'as_named' },
  { auditRow: '074', name: 'tørket dill', id: 'dill_dried', form: 'as_named' },
  { auditRow: '074', name: 'finhakket dill', id: 'dill_fresh', form: 'chopped' },
  { auditRow: '074', name: 'litt frisk dill', id: 'dill_fresh', form: 'as_named' },
  { auditRow: '075', name: 'gressløk', id: 'r075', form: 'as_named' },
  { auditRow: '075', name: 'finhakket gressløk', id: 'r075', form: 'chopped' },
  { auditRow: '076', name: 'safran', id: 'r076', form: 'as_named' },
  { auditRow: '077', name: 'brokkoli', id: 'broccoli', form: 'as_named' },
  { auditRow: '077', name: 'brokkolini', id: 'broccolini', form: 'as_named' },
  { auditRow: '078', name: 'sylteagurk', id: 'pickle_cucumber', form: 'as_named' },
  { auditRow: '078', name: 'cornichons', id: 'cornichon', form: 'as_named' },
  { auditRow: '078', name: 'finhakket sylteagurk', id: 'pickle_cucumber', form: 'chopped' },
  { auditRow: '078', name: 'lake fra sylteagurken', id: 'byproduct_pickle_brine', form: 'byproduct_not_purchased' },
  { auditRow: '079', name: 'vaniljeekstrakt', id: 'vanilla_extract', form: 'as_named' },
  { auditRow: '079', name: 'vaniljepaste', id: 'vanilla_paste', form: 'as_named' },
  { auditRow: '080', name: 'maisenna', id: 'cornstarch', form: 'as_named' },
  { auditRow: '080', name: 'maizena', id: 'cornstarch', form: 'as_named' },
  { auditRow: '081', name: 'kokosmelk', id: 'r081', form: 'as_named' },
  { auditRow: '081', name: 'boks kokosmelk', id: 'r081', form: 'container_count:boks' },
  { auditRow: '082', name: 'eplecidereddik', id: 'vinegar_cider', form: 'as_named' },
  { auditRow: '082', name: 'eplecider', id: 'cider_drink', form: 'as_named' },
  { auditRow: '083', name: 'kapers', id: 'r083', form: 'as_named' },
  { auditRow: '084', name: 'hodekål', id: 'cabbage_white', form: 'as_named' },
  { auditRow: '084', name: 'hodekål eller spisskål', id: 'choice_cabbage_white_pointed', form: 'choice' },
  { auditRow: '084', name: 'rødkål eller hodekål', id: 'choice_cabbage_red_white', form: 'choice' },
  { auditRow: '085', name: 'rødvinseddik', id: 'r085', form: 'as_named' },
  { auditRow: '086', name: 'bakepulver', id: 'r086', form: 'as_named' },
  { auditRow: '087', name: 'entrecôte', id: 'r087', form: 'as_named' },
  { auditRow: '088', name: 'rå, pillede scampi', id: 'r088', form: 'as_named' },
  { auditRow: '088', name: 'rå scampi, renset', id: 'r088', form: 'as_named' },
  { auditRow: '088', name: 'rå scampi', id: 'r088', form: 'as_named' },
  { auditRow: '088', name: 'scampi', id: 'r088', form: 'as_named' },
  { auditRow: '088', name: 'rå scampi, pillede', id: 'r088', form: 'as_named' },
  { auditRow: '089', name: 'fiskekraft', id: 'r089', form: 'as_named' },
  { auditRow: '090', name: 'malt kanel', id: 'cinnamon_ground', form: 'as_named' },
  { auditRow: '090', name: 'kanel', id: 'cinnamon_unspecified', form: 'as_named' },
  { auditRow: '091', name: 'pistasjnøtter', id: 'pistachio', form: 'as_named' },
  { auditRow: '091', name: 'knuste pistasjnøtter', id: 'pistachio', form: 'as_named' },
  { auditRow: '091', name: 'usaltede pistasjnøtter', id: 'pistachio_unsalted', form: 'as_named' },
  { auditRow: '092', name: 'balsamicoeddik', id: 'vinegar_balsamic', form: 'as_named' },
  { auditRow: '092', name: 'balsamicokrem', id: 'balsamic_glaze', form: 'as_named' },
  { auditRow: '092', name: 'balsamico', id: 'balsamic_unspecified', form: 'as_named' },
  { auditRow: '092', name: 'balsamicoglaze', id: 'balsamic_glaze', form: 'as_named' },
  { auditRow: '093', name: 'rosmarin', id: 'rosemary_unspecified', form: 'as_named' },
  { auditRow: '093', name: 'frisk rosmarin', id: 'rosemary_fresh', form: 'as_named' },
  { auditRow: '093', name: 'kvister rosmarin', id: 'rosemary_fresh', form: 'sprig' },
  { auditRow: '094', name: 'blandet salat', id: 'salad_mixed', form: 'as_named' },
  { auditRow: '094', name: 'salatblader', id: 'salad_leaf', form: 'leaf' },
  { auditRow: '094', name: 'crisp-salat', id: 'salad_crisp', form: 'as_named' },
  { auditRow: '094', name: 'blandet grønn salat', id: 'salad_mixed', form: 'as_named' },
  { auditRow: '094', name: 'bladsalat', id: 'salad_leaf', form: 'as_named' },
  { auditRow: '094', name: 'salat', id: 'salad_unspecified', form: 'as_named' },
  { auditRow: '095', name: 'sriracha', id: 'sriracha', form: 'as_named' },
  { auditRow: '095', name: 'sriracha mayo', id: 'sriracha_mayo', form: 'as_named' },
  { auditRow: '096', name: 'mørk sjokolade', id: 'r096', form: 'as_named' },
  { auditRow: '096', name: 'revet mørk sjokolade', id: 'r096', form: 'grated' },
  { auditRow: '097', name: 'hvit pepper', id: 'r097', form: 'as_named' },
  { auditRow: '097', name: 'litt hvit pepper', id: 'r097', form: 'as_named' },
  { auditRow: '097', name: 'hvitt pepper', id: 'r097', form: 'as_named' },
  { auditRow: '098', name: 'hjertesalat', id: 'r098', form: 'as_named' },
  { auditRow: '098', name: 'liten hjertesalat', id: 'r098', form: 'as_named' },
  { auditRow: '098', name: 'blader hjertesalat', id: 'r098', form: 'leaf' },
  { auditRow: '099', name: 'frisk mynte', id: 'mint_fresh', form: 'as_named' },
  { auditRow: '099', name: 'tørket mynte', id: 'mint_dried', form: 'as_named' },
  { auditRow: '099', name: 'mynte', id: 'mint_unspecified', form: 'as_named' },
  { auditRow: '099', name: 'fersk mynte', id: 'mint_fresh', form: 'as_named' },
  { auditRow: '100', name: 'kalamataoliven', id: 'olive_kalamata', form: 'as_named' },
  { auditRow: '100', name: 'kalamataoliven eller sorte oliven', id: 'choice_olive_kalamata_black', form: 'choice' },
  { auditRow: '100', name: 'oliven', id: 'olive_unspecified', form: 'as_named' },
  { auditRow: '100', name: 'sorte eller grønne oliven', id: 'choice_olive_black_green', form: 'choice' },
  { auditRow: '100', name: 'sorte oliven uten stein', id: 'olive_black_pitted', form: 'as_named' },
  { auditRow: '100', name: 'svarte oliven', id: 'olive_black', form: 'as_named' },
  { auditRow: '101', name: 'valnøtter', id: 'r101', form: 'as_named' },
  { auditRow: '102', name: 'revet ost', id: 'r102', form: 'grated' },
  { auditRow: '103', name: 'natron', id: 'r103', form: 'as_named' },
  { auditRow: '104', name: 'couscous', id: 'r104', form: 'as_named' },
  { auditRow: '105', name: 'halloumi', id: 'r105', form: 'as_named' },
  { auditRow: '106', name: 'melis', id: 'r106', form: 'as_named' },
  { auditRow: '107', name: 'isbergsalat', id: 'r107', form: 'as_named' },
  { auditRow: '107', name: 'finstrimlet isbergsalat', id: 'r107', form: 'as_named' },
  { auditRow: '108', name: 'purre', id: 'r108', form: 'as_named' },
  { auditRow: '108', name: 'liten purre', id: 'r108', form: 'as_named' },
  { auditRow: '109', name: 'frosne pommes frites', id: 'fries_frozen', form: 'as_named' },
  { auditRow: '109', name: 'pommes frites', id: 'fries_unspecified', form: 'as_named' },
  { auditRow: '109', name: 'pommes pavé', id: 'review_potato_pave', form: 'review' },
  { auditRow: '110', name: 'stilker stangselleri', id: 'r110', form: 'stalk' },
  { auditRow: '110', name: 'stangselleri', id: 'r110', form: 'as_named' },
  { auditRow: '110', name: 'stilk stangselleri', id: 'r110', form: 'stalk' },
  { auditRow: '111', name: 'grønne asparges', id: 'r111', form: 'as_named' },
  { auditRow: '111', name: 'asparges', id: 'r111', form: 'as_named' },
  { auditRow: '111', name: 'grønn asparges', id: 'r111', form: 'as_named' },
  { auditRow: '112', name: 'mango', id: 'r112', form: 'as_named' },
  { auditRow: '112', name: 'moden mango', id: 'r112', form: 'as_named' },
  { auditRow: '113', name: 'svinefilet', id: 'pork_fillet_unspecified', form: 'as_named' },
  { auditRow: '113', name: 'indrefilet av svin', id: 'pork_tenderloin', form: 'as_named' },
  { auditRow: '113', name: 'ytrefilet av svin', id: 'pork_loin', form: 'as_named' },
  { auditRow: '114', name: 'smør til steking', id: 'butter', form: 'as_named' },
  { auditRow: '114', name: 'smør til brødet', id: 'butter', form: 'as_named' },
  { auditRow: '114', name: 'smør til muffinsene', id: 'butter', form: 'as_named' },
  { auditRow: '114', name: 'smør til formene', id: 'butter', form: 'as_named' },
  { auditRow: '114', name: 'hvetemel til formene', id: 'wheat_flour', form: 'as_named' },
  { auditRow: '115', name: 'kalvefond', id: 'veal_fond', form: 'as_named' },
  { auditRow: '115', name: 'kalvekraft eller oksekraft', id: 'choice_stock_veal_beef', form: 'choice' },
  { auditRow: '115', name: 'kalvfond', id: 'veal_fond', form: 'as_named' },
  { auditRow: '116', name: 'tyttebærsyltetøy', id: 'jam_lingonberry', form: 'as_named' },
  { auditRow: '116', name: 'solbærsyltetøy', id: 'jam_blackcurrant', form: 'as_named' },
  { auditRow: '117', name: 'gochujang', id: 'r117', form: 'as_named' },
  { auditRow: '118', name: 'fiskesaus', id: 'r118', form: 'as_named' },
  { auditRow: '119', name: 'høyrygg av storfe', id: 'r119', form: 'as_named' },
  { auditRow: '120', name: 'gruyère', id: 'r120', form: 'as_named' },
  { auditRow: '121', name: 'sukkererter', id: 'r121', form: 'as_named' },
  { auditRow: '122', name: 'haricots verts', id: 'r122', form: 'as_named' },
  { auditRow: '122', name: 'grønne bønner', id: 'r122', form: 'as_named' },
  { auditRow: '123', name: 'indrefilet av storfe', id: 'r123', form: 'as_named' },
  { auditRow: '123', name: 'midtstykke av indrefilet av storfe', id: 'r123', form: 'as_named' },
  { auditRow: '124', name: 'prosciutto', id: 'prosciutto', form: 'as_named' },
  { auditRow: '124', name: 'spekeskinke', id: 'cured_ham_unspecified', form: 'as_named' },
  { auditRow: '125', name: 'ricotta', id: 'ricotta', form: 'as_named' },
  { auditRow: '125', name: 'ricotta salata', id: 'ricotta_salata', form: 'as_named' },
  { auditRow: '126', name: 'malt koriander', id: 'coriander_ground', form: 'as_named' },
  { auditRow: '126', name: 'koriander krydder', id: 'coriander_spice_unspecified', form: 'as_named' },
  { auditRow: '127', name: 'grønn pesto', id: 'pesto_green', form: 'as_named' },
  { auditRow: '127', name: 'pesto', id: 'pesto_unspecified', form: 'as_named' },
  { auditRow: '128', name: 'rød currypaste', id: 'r128', form: 'as_named' },
  { auditRow: '128', name: 'rød curry paste', id: 'r128', form: 'as_named' },
  { auditRow: '129', name: 'eddik', id: 'vinegar_unspecified', form: 'as_named' },
  { auditRow: '129', name: '7 % eddik', id: 'vinegar_7pct', form: 'as_named' },
  { auditRow: '130', name: 'ansjosfileter', id: 'anchovy_unspecified', form: 'as_named' },
  { auditRow: '130', name: 'ansjosfilet', id: 'anchovy_unspecified', form: 'as_named' },
  { auditRow: '130', name: 'ansjosfileter i olje', id: 'anchovy_oil', form: 'as_named' },
  { auditRow: '131', name: 'lammebog eller annet grytekjøtt av lam', id: 'choice_lamb_shoulder_stew', form: 'choice' },
  { auditRow: '131', name: 'lammeskanker', id: 'lamb_shank', form: 'as_named' },
  { auditRow: '131', name: 'fårikålkjøtt av lam', id: 'lamb_farikal', form: 'as_named' },
  { auditRow: '131', name: 'benfritt lammekjøtt', id: 'lamb_boneless', form: 'as_named' },
  { auditRow: '132', name: 'pecorino romano', id: 'r132', form: 'as_named' },
  { auditRow: '133', name: 'garam masala', id: 'r133', form: 'as_named' },
  { auditRow: '134', name: 'mascarpone', id: 'r134', form: 'as_named' },
  { auditRow: '135', name: 'kremost', id: 'r135', form: 'as_named' },
  { auditRow: '136', name: 'vaniljestang', id: 'r136', form: 'as_named' },
  { auditRow: '137', name: 'blåskjell', id: 'r137', form: 'as_named' },
  { auditRow: '138', name: 'svarte bønner', id: 'r138', form: 'as_named' },
  { auditRow: '139', name: 'kidneybønner', id: 'r139', form: 'as_named' },
  { auditRow: '140', name: 'chorizo', id: 'r140', form: 'as_named' },
  { auditRow: '141', name: 'vaniljeis', id: 'r141', form: 'as_named' },
  { auditRow: '141', name: 'god vaniljeis', id: 'r141', form: 'as_named' },
  { auditRow: '142', name: 'eple', id: 'r142', form: 'as_named' },
  { auditRow: '142', name: 'syrlige epler', id: 'r142', form: 'as_named' },
  { auditRow: '143', name: 'risottoris', id: 'risotto_rice', form: 'as_named' },
  { auditRow: '143', name: 'arborioris', id: 'rice_arborio', form: 'as_named' },
  { auditRow: '144', name: 'auberginer', id: 'r144', form: 'as_named' },
  { auditRow: '144', name: 'store auberginer', id: 'r144', form: 'as_named' },
  { auditRow: '144', name: 'aubergine', id: 'r144', form: 'as_named' },
  { auditRow: '145', name: 'cayennepepper', id: 'r145', form: 'as_named' },
  { auditRow: '145', name: 'cayenne', id: 'r145', form: 'as_named' },
  { auditRow: '145', name: 'litt cayennepepper', id: 'r145', form: 'as_named' },
  { auditRow: '146', name: 'estragon', id: 'tarragon_unspecified', form: 'as_named' },
  { auditRow: '146', name: 'frisk estragon', id: 'tarragon_fresh', form: 'as_named' },
  { auditRow: '146', name: 'finhakket frisk estragon', id: 'tarragon_fresh', form: 'chopped' },
  { auditRow: '146', name: 'tørket estragon', id: 'tarragon_dried', form: 'as_named' },
  { auditRow: '147', name: 'kjøttkraft', id: 'stock_meat', form: 'as_named' },
  { auditRow: '147', name: 'kjøttbuljong-terning', id: 'bouillon_meat_cube', form: 'as_named' },
  { auditRow: '147', name: 'kraft fra stekingen, supplert med kjøttkraft ved behov', id: 'compound_cooking_stock_topup', form: 'byproduct_plus_added_purchase' },
  { auditRow: '148', name: 'rå salsiccia', id: 'r148', form: 'as_named' },
  { auditRow: '148', name: 'salsiccia', id: 'r148', form: 'as_named' },
  { auditRow: '149', name: 'salt og pepper', id: 'compound_salt_pepper', form: 'as_named' },
  { auditRow: '149', name: 'salt og sort pepper', id: 'compound_salt_pepper', form: 'as_named' },
  { auditRow: '149', name: 'salt og nykvernet pepper', id: 'compound_salt_pepper', form: 'as_named' },
  { auditRow: '150', name: 'squash', id: 'r150', form: 'as_named' },
  { auditRow: '150', name: 'liten squash', id: 'r150', form: 'as_named' },
  { auditRow: '150', name: 'middels squash', id: 'r150', form: 'as_named' },
  { auditRow: '151', name: 'strimler appelsinskall', id: 'orange', form: 'peel_strip' },
  { auditRow: '151', name: 'appelsin', id: 'orange', form: 'context_required' },
  { auditRow: '151', name: 'appelsinfileter', id: 'orange', form: 'segment' },
  { auditRow: '151', name: 'ferskpresset appelsinjuice', id: 'orange', form: 'juice' },
  { auditRow: '151', name: 'finrevet skall av 1 appelsin', id: 'orange', form: 'zest_fruit_count:1' },
  { auditRow: '151', name: 'appelsinjuice', id: 'orange_juice', form: 'as_named' },
  { auditRow: '152', name: 'karri', id: 'curry_unspecified', form: 'as_named' },
  { auditRow: '152', name: 'mildt currypulver', id: 'curry_powder_mild', form: 'as_named' },
  { auditRow: '152', name: 'yellow curry', id: 'yellow_curry_paste', form: 'paste' },
  { auditRow: '152', name: 'yellow curry paste', id: 'yellow_curry_paste', form: 'paste' },
  { auditRow: '152', name: 'mildt karripulver', id: 'curry_powder_mild', form: 'as_named' },
  { auditRow: '153', name: 'gnocchi', id: 'gnocchi_unspecified', form: 'as_named' },
  { auditRow: '153', name: 'potetgnocchi', id: 'gnocchi_potato', form: 'as_named' },
  { auditRow: '153', name: 'fersk potetgnocchi', id: 'gnocchi_potato_fresh', form: 'as_named' },
  { auditRow: '153', name: 'fersk gnocchi', id: 'gnocchi_fresh', form: 'as_named' },
  { auditRow: '154', name: 'kalvefilet', id: 'veal_fillet', form: 'as_named' },
  { auditRow: '154', name: 'skiver kalveskank', id: 'veal_shank', form: 'slice' },
  { auditRow: '154', name: 'kalveschnitzel', id: 'veal_schnitzel', form: 'as_named' },
  { auditRow: '154', name: 'kalvestek', id: 'veal_roast', form: 'as_named' },
  { auditRow: '155', name: 'usaltede peanøtter', id: 'peanut_unsalted', form: 'as_named' },
  { auditRow: '155', name: 'peanøttsmør', id: 'peanut_butter', form: 'as_named' },
  { auditRow: '155', name: 'ristede peanøtter', id: 'peanut_roasted', form: 'as_named' },
  { auditRow: '155', name: 'hakkede peanøtter', id: 'peanut', form: 'as_named' },
  { auditRow: '156', name: 'crème fraîche', id: 'r156', form: 'as_named' },
  { auditRow: '157', name: 'mais', id: 'r157', form: 'as_named' },
  { auditRow: '158', name: 'svinenakke', id: 'r158', form: 'as_named' },
  { auditRow: '159', name: 'mirin', id: 'r159', form: 'as_named' },
  { auditRow: '160', name: 'pak choi', id: 'r160', form: 'as_named' },
  { auditRow: '161', name: 'ketchup', id: 'r161', form: 'as_named' },
  { auditRow: '162', name: 'bringebær', id: 'raspberry', form: 'as_named' },
  { auditRow: '162', name: 'friske bringebær', id: 'raspberry_fresh', form: 'as_named' },
  { auditRow: '163', name: 'tzatziki', id: 'r163', form: 'as_named' },
  { auditRow: '164', name: 'syltet jalapeño', id: 'r164', form: 'as_named' },
  { auditRow: '165', name: 'potetmel', id: 'r165', form: 'as_named' },
  { auditRow: '166', name: 'naan', id: 'r166', form: 'as_named' },
  { auditRow: '167', name: 'hvitvinseddik', id: 'r167', form: 'as_named' },
  { auditRow: '168', name: 'blomkål', id: 'r168', form: 'as_named' },
  { auditRow: '168', name: 'liten blomkål', id: 'r168', form: 'as_named' },
  { auditRow: '169', name: 'marsala', id: 'marsala', form: 'as_named' },
  { auditRow: '169', name: 'kahlúa, marsala eller mørk rom', id: 'choice_kahlua_marsala_rum', form: 'choice' },
  { auditRow: '170', name: 'gul sennep', id: 'mustard_yellow', form: 'as_named' },
  { auditRow: '170', name: 'grov sennep med hele sennepsfrø', id: 'mustard_wholegrain', form: 'as_named' },
  { auditRow: '171', name: 'kikerter', id: 'r171', form: 'as_named' },
  { auditRow: '171', name: 'boks kikerter', id: 'r171', form: 'container_count:boks' },
  { auditRow: '172', name: 'kveitefilet', id: 'r172', form: 'as_named' },
  { auditRow: '172', name: 'kveitefilet uten skinn', id: 'r172', form: 'as_named' },
  { auditRow: '173', name: 'ristede pinjekjerner', id: 'pinenuts_roasted', form: 'as_named' },
  { auditRow: '173', name: 'pinjekjerner', id: 'pinenuts', form: 'as_named' },
  { auditRow: '174', name: 'eggnudler', id: 'noodles_egg', form: 'as_named' },
  { auditRow: '174', name: 'risnudler', id: 'noodles_rice', form: 'as_named' },
  { auditRow: '175', name: 'østerssaus', id: 'r175', form: 'as_named' },
  { auditRow: '175', name: 'oystersaus', id: 'r175', form: 'as_named' },
  { auditRow: '176', name: 'favabønner', id: 'fava_beans', form: 'as_named' },
  { auditRow: '176', name: 'butterbeans', id: 'butter_beans', form: 'as_named' },
  { auditRow: '176', name: 'butter beans', id: 'butter_beans', form: 'as_named' },
  { auditRow: '177', name: 'bakekakao', id: 'r177', form: 'as_named' },
  { auditRow: '177', name: 'usøtet kakao', id: 'r177', form: 'as_named' },
  { auditRow: '177', name: 'kakaopulver', id: 'r177', form: 'as_named' },
  { auditRow: '178', name: 'små baguetter', id: 'baguette_small', form: 'as_named' },
  { auditRow: '178', name: 'skiver baguette', id: 'baguette', form: 'slice' },
  { auditRow: '178', name: 'baguette', id: 'baguette', form: 'as_named' },
  { auditRow: '179', name: 'små romanosalater', id: 'r179', form: 'as_named' },
  { auditRow: '179', name: 'liten romanosalat', id: 'r179', form: 'as_named' },
  { auditRow: '179', name: 'romanosalat', id: 'r179', form: 'as_named' },
  { auditRow: '180', name: 'tunfisk i olivenolje', id: 'tuna_canned_oliveoil', form: 'as_named' },
  { auditRow: '180', name: 'tunfisk', id: 'tuna_unspecified', form: 'as_named' },
  { auditRow: '180', name: 'tunfisk i olje', id: 'tuna_canned_oil', form: 'as_named' },
  { auditRow: '181', name: 'lønnesirup', id: 'r181', form: 'as_named' },
  { auditRow: '182', name: 'pancetta', id: 'r182', form: 'as_named' },
  { auditRow: '183', name: 'chèvre', id: 'r183', form: 'as_named' },
  { auditRow: '184', name: 'blåmuggost', id: 'r184', form: 'as_named' },
  { auditRow: '185', name: 'guanciale', id: 'r185', form: 'as_named' },
  { auditRow: '186', name: 'røde druer', id: 'r186', form: 'as_named' },
  { auditRow: '187', name: 'melkesjokolade', id: 'r187', form: 'as_named' },
  { auditRow: '188', name: 'kefir', id: 'r188', form: 'as_named' },
  { auditRow: '189', name: 'granateplekjerner', id: 'pomegranate_seeds', form: 'as_named' },
  { auditRow: '189', name: 'granateplemelasse', id: 'pomegranate_molasses', form: 'as_named' },
  { auditRow: '190', name: 'kyllingkjøttdeig', id: 'r190', form: 'as_named' },
  { auditRow: '191', name: 'havregryn', id: 'r191', form: 'as_named' },
  { auditRow: '192', name: 'hummus', id: 'r192', form: 'as_named' },
  { auditRow: '193', name: 'cognac', id: 'r193', form: 'as_named' },
  { auditRow: '194', name: 'einebær', id: 'r194', form: 'as_named' },
  { auditRow: '195', name: 'viltkraft eller oksekraft', id: 'choice_r195', form: 'choice' },
  { auditRow: '196', name: 'jordbær', id: 'r196', form: 'as_named' },
  { auditRow: '197', name: 'malt allehånde', id: 'r197', form: 'as_named' },
  { auditRow: '198', name: 'sumak', id: 'r198', form: 'as_named' },
  { auditRow: '199', name: 'store kamskjell', id: 'r199', form: 'as_named' },
  { auditRow: '200', name: 'kimchi', id: 'r200', form: 'as_named' },
  { auditRow: '201', name: 'sellerirot', id: 'r201', form: 'as_named' },
  { auditRow: '202', name: 'lammecarré', id: 'r202', form: 'as_named' },
  { auditRow: '203', name: 'pastinakker', id: 'r203', form: 'as_named' },
  { auditRow: '204', name: 'kålrot', id: 'r204', form: 'as_named' },
  { auditRow: '205', name: 'fast tofu', id: 'r205', form: 'as_named' },
  { auditRow: '206', name: 'andebryst med skinn', id: 'duck_breast_skin', form: 'as_named' },
  { auditRow: '206', name: 'andefett', id: 'duck_fat', form: 'as_named' },
  { auditRow: '206', name: 'confiterte andelår', id: 'duck_leg_confit', form: 'as_named' },
  { auditRow: '207', name: 'faste pærer', id: 'r207', form: 'as_named' },
  { auditRow: '207', name: 'pære', id: 'r207', form: 'as_named' },
  { auditRow: '208', name: 'chipotlepaste', id: 'chipotle_paste', form: 'as_named' },
  { auditRow: '208', name: 'chipotle i adobo', id: 'chipotle_adobo', form: 'as_named' },
  { auditRow: '209', name: 'fennikel', id: 'fennel_bulb', form: 'as_named' },
  { auditRow: '209', name: 'fennikelfrø', id: 'fennel_seed', form: 'as_named' },
  { auditRow: '210', name: 'salsa', id: 'salsa_unspecified', form: 'as_named' },
  { auditRow: '210', name: 'salsa verde', id: 'salsa_verde', form: 'as_named' },
  { auditRow: '211', name: 'finsnittet rødkål', id: 'r211', form: 'as_named' },
  { auditRow: '211', name: 'rødkål', id: 'r211', form: 'as_named' },
  { auditRow: '212', name: 'frisk salvie', id: 'sage_fresh', form: 'as_named' },
  { auditRow: '212', name: 'friske salvieblader', id: 'sage_fresh', form: 'leaf' },
  { auditRow: '212', name: 'salvieblader', id: 'sage_fresh', form: 'leaf' },
  { auditRow: '213', name: 'pitabrød', id: 'pita', form: 'as_named' },
  { auditRow: '213', name: 'greske pitabrød', id: 'pita_greek', form: 'as_named' },
  { auditRow: '214', name: 'ytrefilet av storfe', id: 'beef_sirloin', form: 'as_named' },
  { auditRow: '214', name: 'ytrefilet eller entrecote', id: 'choice_beef_sirloin_ribeye', form: 'choice' },
  { auditRow: '215', name: 'tørrgjær', id: 'yeast_dry', form: 'as_named' },
  { auditRow: '215', name: 'fersk gjær', id: 'yeast_fresh', form: 'as_named' },
  { auditRow: '216', name: 'røde linser', id: 'lentils_red', form: 'as_named' },
  { auditRow: '216', name: 'pakke ferdigkokte grønne linser', id: 'lentils_green_cooked', form: 'as_named' },
  { auditRow: '217', name: 'persisk flatbrød', id: 'flatbread_persian', form: 'as_named' },
  { auditRow: '217', name: 'flatbrød', id: 'flatbread_unspecified', form: 'as_named' },
  { auditRow: '218', name: 'lys misopaste', id: 'miso_light', form: 'as_named' },
  { auditRow: '218', name: 'miso', id: 'miso_unspecified', form: 'as_named' },
  { auditRow: '219', name: 'lammedeig', id: 'r219', form: 'as_named' },
  { auditRow: '219', name: 'kjøttdeig av lam', id: 'r219', form: 'as_named' },
  { auditRow: '220', name: 'mild røkt kjøttpølse', id: 'sausage_mild_smoked', form: 'as_named' },
  { auditRow: '220', name: 'kjøttpølse', id: 'sausage_meat_unspecified', form: 'as_named' },
  { auditRow: '221', name: 'seifilet', id: 'pollock_fillet', form: 'as_named' },
  { auditRow: '221', name: 'torskefilet eller seifilet', id: 'choice_cod_pollock', form: 'choice' },
  { auditRow: '222', name: 'cannellinibønner', id: 'r222', form: 'as_named' },
  { auditRow: '222', name: 'bokser cannellinibønner', id: 'r222', form: 'container_count:boks' },
  { auditRow: '223', name: 'berberis', id: 'barberry_unspecified', form: 'as_named' },
  { auditRow: '223', name: 'tørkede berberis', id: 'barberry_dried', form: 'as_named' },
  { auditRow: '224', name: 'sterk kaffe', id: 'coffee_brewed', form: 'as_named' },
  { auditRow: '224', name: 'espressopulver', id: 'espresso_powder', form: 'as_named' },
  { auditRow: '225', name: 'kashk', id: 'r225', form: 'as_named' },
  { auditRow: '226', name: 'shaoxing-vin', id: 'r226', form: 'as_named' },
  { auditRow: '227', name: 'cajun-krydder', id: 'r227', form: 'as_named' },
  { auditRow: '228', name: 'kirsebær', id: 'r228', form: 'as_named' },
  { auditRow: '229', name: 'hoisinsaus', id: 'r229', form: 'as_named' },
  { auditRow: '230', name: 'bao buns', id: 'r230', form: 'as_named' },
  { auditRow: '231', name: 'friske bær', id: 'r231', form: 'as_named' },
  { auditRow: '232', name: 'bbq-saus', id: 'r232', form: 'as_named' },
  { auditRow: '233', name: 'butterdeig', id: 'r233', form: 'as_named' },
  { auditRow: '234', name: 'næringsgjær', id: 'r234', form: 'as_named' },
  { auditRow: '235', name: 'frank\'s redhot original', id: 'r235', form: 'as_named' },
  { auditRow: '236', name: 'harissa', id: 'r236', form: 'as_named' },
  { auditRow: '237', name: 'grand marnier', id: 'r237', form: 'as_named' },
  { auditRow: '238', name: 'sake', id: 'r238', form: 'as_named' },
  { auditRow: '239', name: 'kokt skinke', id: 'r239', form: 'as_named' },
  { auditRow: '240', name: 'vinblader i lake', id: 'r240', form: 'leaf' },
  { auditRow: '241', name: 'english muffins', id: 'r241', form: 'as_named' },
  { auditRow: '242', name: 'rød enchiladasaus', id: 'r242', form: 'as_named' },
  { auditRow: '243', name: 'falafel', id: 'r243', form: 'as_named' },
  { auditRow: '244', name: 'tahini', id: 'r244', form: 'as_named' },
  { auditRow: '245', name: 'reinsdyrskav', id: 'r245', form: 'as_named' },
  { auditRow: '246', name: 'kaldt lyst øl', id: 'r246', form: 'as_named' },
  { auditRow: '247', name: 'malteddik', id: 'r247', form: 'as_named' },
  { auditRow: '248', name: 'sherryeddik', id: 'r248', form: 'as_named' },
  { auditRow: '249', name: 'tykke skiver brioche', id: 'r249', form: 'slice' },
  { auditRow: '250', name: 'tørket bukkehornkløver', id: 'r250', form: 'as_named' },
  { auditRow: '251', name: 'sambal', id: 'r251', form: 'as_named' },
  { auditRow: '252', name: 'vannmelon', id: 'r252', form: 'as_named' },
  { auditRow: '253', name: 'ringer fersk ananas', id: 'r253', form: 'as_named' },
  { auditRow: '254', name: 'remulade', id: 'r254', form: 'as_named' },
  { auditRow: '255', name: 'ferdigkokte hummerhaler, ca. 250–300 g med skall', id: 'r255', form: 'as_named' },
  { auditRow: '256', name: 'aioli', id: 'r256', form: 'as_named' },
  { auditRow: '257', name: 'blokker japansk curry roux', id: 'r257', form: 'as_named' },
  { auditRow: '258', name: 'hasselnøtter', id: 'r258', form: 'as_named' },
  { auditRow: '259', name: 'malt kardemomme', id: 'r259', form: 'as_named' },
  { auditRow: '260', name: 'tørkede plommer uten stein', id: 'r260', form: 'as_named' },
  { auditRow: '261', name: 'gelatinplater', id: 'r261', form: 'as_named' },
  { auditRow: '262', name: 'kokosflak', id: 'r262', form: 'as_named' },
  { auditRow: '263', name: 'pillede reker', id: 'r263', form: 'as_named' },
  { auditRow: '264', name: 'fersk tortellini med ost', id: 'r264', form: 'as_named' },
  { auditRow: '265', name: 'hjortekjøtt til gryte', id: 'r265', form: 'as_named' },
  { auditRow: '266', name: 'sichuanpepper', id: 'r266', form: 'as_named' },
  { auditRow: '267', name: 'kinesisk svart eddik', id: 'r267', form: 'as_named' },
  { auditRow: '268', name: 'champagne eller tørr musserende vin', id: 'choice_r268', form: 'choice' },
  { auditRow: '269', name: 'reddiker', id: 'r269', form: 'as_named' },
  { auditRow: '270', name: 'cashewnøtter', id: 'r270', form: 'as_named' },
  { auditRow: '271', name: 'thai krydder', id: 'r271', form: 'as_named' },
  { auditRow: '272', name: 'lammekraft eller oksekraft', id: 'choice_r272', form: 'choice' },
  { auditRow: '273', name: 'hjerteskjell', id: 'r273', form: 'as_named' },
  { auditRow: '274', name: 'rødbeter', id: 'r274', form: 'as_named' },
  { auditRow: '275', name: 'digestive-kjeks', id: 'r275', form: 'as_named' },
  { auditRow: '276', name: 'gyoza', id: 'r276', form: 'as_named' },
  { auditRow: '277', name: 'ponzasaus', id: 'r277', form: 'as_named' },
  { auditRow: '278', name: 'chiliolje', id: 'r278', form: 'as_named' },
  { auditRow: '279', name: 'ørretfilet', id: 'r279', form: 'as_named' },
  { auditRow: '280', name: 'skreifilet', id: 'r280', form: 'as_named' },
  { auditRow: '281', name: 'paellaris', id: 'r281', form: 'as_named' },
  { auditRow: '282', name: 'paneer', id: 'r282', form: 'as_named' },
  { auditRow: '283', name: 'smør eller ghee', id: 'choice_r283', form: 'choice' },
  { auditRow: '284', name: 'breiflabbfilet', id: 'r284', form: 'as_named' },
  { auditRow: '285', name: 'urter', id: 'r285', form: 'as_named' },
  { auditRow: '286', name: 'matfløte', id: 'r286', form: 'as_named' },
  { auditRow: '287', name: 'blåbær', id: 'r287', form: 'as_named' },
  { auditRow: '288', name: 'sushiris', id: 'r288', form: 'as_named' },
  { auditRow: '289', name: 'edamamebønner', id: 'r289', form: 'as_named' },
  { auditRow: '290', name: 'tynnribbe', id: 'r290', form: 'as_named' },
  { auditRow: '291', name: 'cottage cheese', id: 'r291', form: 'as_named' },
  { auditRow: '292', name: 'proteinpulver', id: 'r292', form: 'as_named' },
  { auditRow: '293', name: 'eplejuice', id: 'r293', form: 'as_named' },
  { auditRow: '294', name: 'vodka', id: 'r294', form: 'as_named' },
  { auditRow: '295', name: 'nduja', id: 'r295', form: 'as_named' },
  { auditRow: '296', name: 'rogn', id: 'r296', form: 'as_named' },
  { auditRow: '297', name: 'camembert', id: 'r297', form: 'as_named' },
  { auditRow: '298', name: 'makrellfilet', id: 'r298', form: 'as_named' },
  { auditRow: '299', name: 'uerfilet', id: 'r299', form: 'as_named' },
  { auditRow: '300', name: 'dadler', id: 'r300', form: 'as_named' },
  { auditRow: '301', name: 'kjøttdeig av svin', id: 'r301', form: 'as_named' },
  { auditRow: '302', name: 'calvados', id: 'r302', form: 'as_named' },
  { auditRow: '303', name: 'svinekam med svor', id: 'r303', form: 'as_named' },
  { auditRow: '304', name: 'savoiardi (ladyfingers)', id: 'r304', form: 'as_named' },
  { auditRow: '305', name: 'grønnkål', id: 'r305', form: 'as_named' },
  { auditRow: '306', name: 'trøffelpaste', id: 'r306', form: 'as_named' },
  { auditRow: '307', name: 'karvefrø', id: 'r307', form: 'as_named' },
  { auditRow: '308', name: 'stilk sitrongress', id: 'r308', form: 'stalk' },
  { auditRow: '309', name: 'bønnespirer', id: 'r309', form: 'as_named' },
  { auditRow: 'U1', name: 'stekesmør fra biff', id: 'byproduct_steak_butter', form: 'byproduct_not_purchased' },
  { auditRow: 'U2', name: 'salt lammekjøtt eller saltkjøtt av får', id: 'choice_salted_lamb_mutton', form: 'choice_salted_meat' },
  { auditRow: 'U2', name: 'salt lammekjøtt', id: 'salted_lamb', form: 'salted_meat' },
  { auditRow: 'U2', name: 'saltkjøtt av får', id: 'salted_mutton', form: 'salted_meat' },
];

export interface PurchaseMainRow {
  name: string;
  treatment: string;
  ids: string[];
  pantry: string;
  confidence: string;
}

export const PURCHASE_MAIN_ROWS: PurchaseMainRow[] = [
  { name: 'Salt', treatment: 'KEEP + PANTRY', ids: ['salt', 'salt_fine', 'salt_flake', 'salt_coarse'], pantry: 'Delvis; se produktliste', confidence: 'HIGH' },
  { name: 'Sort pepper', treatment: 'KEEP + PANTRY', ids: ['pepper_black_ground', 'pepper_unspecified', 'pepper_black_whole', 'pepper_black_crushed', 'pepper_whole_unspecified'], pantry: 'Delvis; se produktliste', confidence: 'HIGH' },
  { name: 'Hvitløk', treatment: 'KEEP + WHOLE_UNIT + YIELD_CONVERSION + REVIEW', ids: ['garlic', 'garlic_powder', 'garlic_seasoning'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Sitron', treatment: 'KEEP + WHOLE_UNIT + YIELD_CONVERSION', ids: ['lemon', 'lemon_pepper'], pantry: 'Nei', confidence: 'MEDIUM' },
  { name: 'Smør', treatment: 'KEEP + REVIEW', ids: ['butter', 'butter_browned', 'choice_oil_butter'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Olivenolje', treatment: 'KEEP + PANTRY', ids: ['olive_oil', 'olive_oil_extra_virgin'], pantry: 'Delvis; se produktliste', confidence: 'HIGH' },
  { name: 'Nøytral olje', treatment: 'KEEP + PANTRY', ids: ['neutral_oil', 'oil_unspecified'], pantry: 'Delvis; se produktliste', confidence: 'HIGH' },
  { name: 'Gul løk', treatment: 'KEEP + WHOLE_UNIT + REVIEW', ids: ['onion_yellow', 'onion_powder', 'onion_unspecified', 'onion_crispy'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Persille', treatment: 'KEEP + PURCHASE_FORM + REVIEW', ids: ['parsley_flat_fresh', 'parsley_fresh', 'choice_parsley_mint', 'choice_tarragon_parsley'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Potet', treatment: 'KEEP + WHOLE_UNIT', ids: ['potato_small', 'potato', 'potato_floury', 'potato_waxy', 'potato_cooked'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Kremfløte', treatment: 'KEEP', ids: ['r011'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Hvetemel/mel', treatment: 'KEEP + PANTRY + REVIEW', ids: ['wheat_flour', 'barley_flour', 'flour_unspecified'], pantry: 'Delvis; se produktliste', confidence: 'LOW' },
  { name: 'Vann', treatment: 'KEEP + NOT_PURCHASED', ids: ['water', 'tuna_canned_water'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Sukker (hvitt)', treatment: 'KEEP + PANTRY', ids: ['sugar_white', 'sugar_brown'], pantry: 'Delvis; se produktliste', confidence: 'HIGH' },
  { name: 'Parmesan', treatment: 'KEEP', ids: ['parmesan', 'parmigiano_reggiano'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Egg', treatment: 'KEEP + WHOLE_UNIT + YIELD_CONVERSION', ids: ['egg'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Tomat (hermetisk/puré)', treatment: 'KEEP + NOT_PURCHASED + REVIEW', ids: ['tomato_paste', 'tomato_canned_chopped', 'tomato_canned_whole', 'tomato_canned_unspecified', 'tomato_passata', 'tomato_sundried_oil', 'byproduct_tomato_oil', 'tomato_canned_finely_chopped'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Ris (hvit, generisk)', treatment: 'KEEP', ids: ['rice_basmati', 'rice_jasmine', 'rice_unspecified', 'rice_longgrain'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Honning', treatment: 'KEEP', ids: ['r019'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Dijonsennep', treatment: 'KEEP', ids: ['dijon'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Chili', treatment: 'KEEP + WHOLE_UNIT + REVIEW', ids: ['chili_flakes', 'chili_red_fresh', 'chili_powder', 'chili_seasoning', 'choice_pulbiber_aleppo', 'chili_red_dried', 'chili_green_fresh', 'chili_unspecified'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Lime', treatment: 'KEEP + WHOLE_UNIT + YIELD_CONVERSION', ids: ['lime', 'lime_persian_dried'], pantry: 'Nei', confidence: 'MEDIUM' },
  { name: 'Sjalottløk', treatment: 'KEEP + WHOLE_UNIT', ids: ['r023'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Paprikapulver/røkt paprika', treatment: 'KEEP', ids: ['paprika_powder', 'paprika_smoked', 'paprika_sweet_hungarian'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Pasta (tørr, generisk/spesifisert type)', treatment: 'KEEP + REVIEW', ids: ['pasta_pasta', 'pasta_spaghetti', 'pasta_makaroni', 'choice_pasta_linguine_spaghetti', 'choice_pasta_rigatoni_penne', 'pasta_rigatoni', 'pasta_orzo', 'pasta_lasagne', 'pasta_linguine', 'pasta_tagliatelle', 'pasta_bucatini', 'choice_pasta_linguine_eller_tagliatelle', 'pasta_pappardelle', 'choice_pasta_ditalini_eller_annen_liten_pasta', 'pasta_fettuccine', 'choice_pasta_penne_eller_fusilli', 'pasta_trofie'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Timian', treatment: 'KEEP + PURCHASE_FORM + REVIEW', ids: ['thyme_unspecified', 'thyme_fresh', 'thyme_dried'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Oregano', treatment: 'KEEP + PURCHASE_FORM + REVIEW', ids: ['oregano_dried', 'oregano_unspecified'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Kyllingkraft/-buljong', treatment: 'KEEP + NOT_PURCHASED + REVIEW', ids: ['stock_chicken', 'choice_stock_chicken_vegetable', 'bouillon_chicken', 'bouillon_chicken_powder', 'bouillon_chicken_cube', 'byproduct_chicken_stock'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Soyasaus', treatment: 'KEEP', ids: ['r029'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Rødløk', treatment: 'KEEP + WHOLE_UNIT', ids: ['onion_red', 'onion_red_pickled'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Helmelk/melk', treatment: 'KEEP', ids: ['milk_whole', 'milk_unspecified', 'milk_cultured'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Gulrot', treatment: 'KEEP + WHOLE_UNIT', ids: ['r032'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Koriander (fersk)', treatment: 'KEEP + PURCHASE_FORM + REVIEW', ids: ['coriander_fresh', 'choice_thaibasil_coriander'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Pastavann/kokevann', treatment: 'KEEP + PANTRY + NOT_PURCHASED', ids: ['pasta_water', 'salt', 'cooking_water', 'byproduct_poaching_stock', 'byproduct_cooking_stock'], pantry: 'Delvis; se produktliste', confidence: 'HIGH' },
  { name: 'Vårløk', treatment: 'KEEP + WHOLE_UNIT', ids: ['r035'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Kyllinglårfilet', treatment: 'KEEP', ids: ['chicken_thigh_fillet', 'chicken_thigh_bone_skin', 'chicken_thigh', 'chicken_thigh_fillet_skin'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Tomat (fersk)', treatment: 'KEEP + WHOLE_UNIT', ids: ['tomato_cherry', 'tomato_fresh'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Agurk', treatment: 'KEEP + WHOLE_UNIT', ids: ['r038'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Kjøttdeig (storfe)', treatment: 'KEEP + REVIEW', ids: ['mince_unspecified', 'mince_beef', 'mince_beef_lean'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Majones', treatment: 'KEEP', ids: ['r040'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Paprika (frukt)', treatment: 'KEEP + WHOLE_UNIT', ids: ['pepper_red', 'pepper_fruit_unspecified', 'pepper_yellow', 'pepper_green', 'paprika_powder'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Kyllingfilet/bryst', treatment: 'KEEP + REVIEW', ids: ['chicken_breast', 'chicken_unspecified', 'chicken_breast_skin'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Brød (godt/landbrød, generisk)', treatment: 'KEEP + REVIEW', ids: ['bread_generic', 'bread_country', 'bread_white', 'bread_toast', 'choice_bread_sourdough_baguette', 'choice_ham_cooked_smoked'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Ingefær', treatment: 'KEEP + REVIEW', ids: ['ginger_fresh', 'ginger_unspecified', 'ginger_ground'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Panko/brødsmuler', treatment: 'KEEP + REVIEW', ids: ['panko', 'breadcrumbs', 'choice_rusk_panko', 'choice_panko_breadcrumbs'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Basilikum', treatment: 'KEEP + PURCHASE_FORM + REVIEW', ids: ['basil_fresh', 'basil_unspecified', 'basil_thai_fresh', 'basil_dried', 'choice_holy_thai_basil'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Spisskummen', treatment: 'KEEP + REVIEW', ids: ['cumin_ground', 'cumin_unspecified'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Riseddik', treatment: 'KEEP', ids: ['r048'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Sesamfrø', treatment: 'KEEP', ids: ['sesame_seed', 'sesame_seed_roasted'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Gresk yoghurt', treatment: 'KEEP + REVIEW', ids: ['yoghurt_greek', 'review_berries_yoghurt_syrup'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Hvitvin (tørr)', treatment: 'KEEP', ids: ['r051'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Sjampinjong/aromasopp', treatment: 'KEEP + REVIEW', ids: ['mushroom_brown', 'choice_mushroom_brown_button', 'mushroom_button', 'mushroom_button_mini'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Oksekraft/-buljong', treatment: 'KEEP', ids: ['r053'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Rømme/seterrømme', treatment: 'KEEP', ids: ['sourcream', 'sourcream_seter'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Avokado', treatment: 'KEEP + WHOLE_UNIT', ids: ['r055'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Bacon', treatment: 'KEEP', ids: ['r056'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Mozzarella', treatment: 'KEEP', ids: ['burrata', 'mozzarella_fresh', 'mozzarella_unspecified', 'mozzarella_grated'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Tortilla', treatment: 'KEEP', ids: ['tortilla_small_unspecified', 'tortilla_small_corn', 'tortilla_large_wheat', 'tortilla_unspecified', 'tortilla_large_unspecified', 'tortilla_medium_unspecified', 'tortilla_small_wheat'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Sesamolje', treatment: 'KEEP', ids: ['r059'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Worcestershiresaus', treatment: 'KEEP', ids: ['r060'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Laurbærblad', treatment: 'KEEP', ids: ['r061'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Gurkemeie', treatment: 'KEEP + REVIEW', ids: ['turmeric_unspecified', 'turmeric_ground'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Babyspinat/spinat', treatment: 'KEEP', ids: ['spinach_baby', 'spinach_fresh'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Grønnsakskraft/-buljong', treatment: 'KEEP + REVIEW', ids: ['stock_vegetable', 'bouillon_vegetable', 'choice_stock_chicken_vegetable'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Feta', treatment: 'KEEP', ids: ['r065'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Laksefilet', treatment: 'KEEP', ids: ['salmon_fillet', 'salmon_fillet_skinless', 'salmon_fillet_skin', 'salmon_unspecified'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Rødvin (tørr)', treatment: 'KEEP', ids: ['r067'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Grønne erter', treatment: 'KEEP', ids: ['peas_green_frozen', 'peas_yellow_split'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Cheddar', treatment: 'KEEP', ids: ['r069'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Rucola', treatment: 'KEEP', ids: ['r070'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Burgerbrød (brioche)', treatment: 'KEEP', ids: ['r071'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Torskefilet', treatment: 'KEEP + REVIEW', ids: ['cod_fillet', 'choice_cod_whitefish', 'choice_cod_loin', 'cod_fillet_skinless'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Muskat', treatment: 'KEEP + REVIEW', ids: ['nutmeg_ground', 'nutmeg_unspecified', 'nutmeg_grated'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Dill', treatment: 'KEEP + PURCHASE_FORM + REVIEW', ids: ['dill_fresh', 'dill_unspecified', 'dill_dried'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Gressløk', treatment: 'KEEP + PURCHASE_FORM + REVIEW', ids: ['r075'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Safran', treatment: 'KEEP', ids: ['r076'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Brokkoli', treatment: 'KEEP + WHOLE_UNIT', ids: ['broccoli', 'broccolini'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Sylteagurk', treatment: 'KEEP + NOT_PURCHASED', ids: ['pickle_cucumber', 'cornichon', 'byproduct_pickle_brine'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Vaniljeekstrakt/-paste', treatment: 'KEEP', ids: ['vanilla_extract', 'vanilla_paste'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Maisennamel/maizena', treatment: 'KEEP', ids: ['cornstarch'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Kokosmelk', treatment: 'KEEP', ids: ['r081'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Eplecidereddik', treatment: 'KEEP + REVIEW', ids: ['vinegar_cider', 'cider_drink'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Kapers', treatment: 'KEEP', ids: ['r083'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Hodekål/spisskål', treatment: 'KEEP + REVIEW', ids: ['cabbage_white', 'choice_cabbage_white_pointed', 'choice_cabbage_red_white'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Rødvinseddik', treatment: 'KEEP', ids: ['r085'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Bakepulver', treatment: 'KEEP', ids: ['r086'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Entrecôte', treatment: 'KEEP', ids: ['r087'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Scampi', treatment: 'KEEP', ids: ['r088'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Fiskekraft', treatment: 'KEEP', ids: ['r089'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Kanel', treatment: 'KEEP + REVIEW', ids: ['cinnamon_ground', 'cinnamon_unspecified'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Pistasjnøtter', treatment: 'KEEP', ids: ['pistachio', 'pistachio_unsalted'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Balsamicoeddik', treatment: 'KEEP + REVIEW', ids: ['vinegar_balsamic', 'balsamic_glaze', 'balsamic_unspecified'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Rosmarin', treatment: 'KEEP + PURCHASE_FORM + REVIEW', ids: ['rosemary_unspecified', 'rosemary_fresh'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Blandet salat', treatment: 'KEEP + REVIEW', ids: ['salad_mixed', 'salad_leaf', 'salad_crisp', 'salad_unspecified'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Sriracha', treatment: 'KEEP', ids: ['sriracha', 'sriracha_mayo'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Mørk sjokolade', treatment: 'KEEP', ids: ['r096'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Hvit pepper', treatment: 'KEEP', ids: ['r097'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Hjertesalat', treatment: 'KEEP + WHOLE_UNIT', ids: ['r098'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Mynte', treatment: 'KEEP + PURCHASE_FORM + REVIEW', ids: ['mint_fresh', 'mint_dried', 'mint_unspecified'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Oliven', treatment: 'KEEP + REVIEW', ids: ['olive_kalamata', 'choice_olive_kalamata_black', 'olive_unspecified', 'choice_olive_black_green', 'olive_black_pitted', 'olive_black'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Valnøtter', treatment: 'KEEP', ids: ['r101'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Generisk ost (revet/ukjent type)', treatment: 'KEEP', ids: ['r102'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Natron', treatment: 'KEEP', ids: ['r103'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Couscous', treatment: 'KEEP', ids: ['r104'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Halloumi', treatment: 'KEEP', ids: ['r105'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Melis', treatment: 'KEEP', ids: ['r106'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Isbergsalat', treatment: 'KEEP + WHOLE_UNIT', ids: ['r107'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Purre', treatment: 'KEEP + WHOLE_UNIT', ids: ['r108'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Pommes frites', treatment: 'KEEP + REVIEW', ids: ['fries_frozen', 'fries_unspecified', 'review_potato_pave'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Stangselleri', treatment: 'KEEP', ids: ['r110'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Asparges', treatment: 'KEEP', ids: ['r111'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Mango', treatment: 'KEEP + WHOLE_UNIT', ids: ['r112'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Svinefilet', treatment: 'KEEP', ids: ['pork_fillet_unspecified', 'pork_tenderloin', 'pork_loin'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Smør/hvetemel til former (tilbehør til bakeform)', treatment: 'KEEP + PANTRY', ids: ['butter', 'wheat_flour'], pantry: 'Delvis; se produktliste', confidence: 'HIGH' },
  { name: 'Kalvekraft/-fond', treatment: 'KEEP + REVIEW', ids: ['veal_fond', 'choice_stock_veal_beef'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Syltetøy (tyttebær/solbær)', treatment: 'KEEP', ids: ['jam_lingonberry', 'jam_blackcurrant'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Gochujang', treatment: 'KEEP', ids: ['r117'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Fiskesaus', treatment: 'KEEP', ids: ['r118'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Høyrygg av storfe', treatment: 'KEEP', ids: ['r119'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Gruyère', treatment: 'KEEP', ids: ['r120'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Sukkererter', treatment: 'KEEP', ids: ['r121'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Grønne bønner', treatment: 'KEEP', ids: ['r122'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Indrefilet av storfe', treatment: 'KEEP', ids: ['r123'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Prosciutto/spekeskinke', treatment: 'KEEP', ids: ['prosciutto', 'cured_ham_unspecified'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Ricotta', treatment: 'KEEP', ids: ['ricotta', 'ricotta_salata'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Koriander (frø/krydder, malt)', treatment: 'KEEP + REVIEW', ids: ['coriander_ground', 'coriander_spice_unspecified'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Pesto', treatment: 'KEEP + REVIEW', ids: ['pesto_green', 'pesto_unspecified'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Currypaste', treatment: 'KEEP', ids: ['r128'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Eddik (generisk, 7%)', treatment: 'KEEP + REVIEW', ids: ['vinegar_unspecified', 'vinegar_7pct'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Ansjos', treatment: 'KEEP', ids: ['anchovy_unspecified', 'anchovy_oil'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Lammekjøtt (grytekjøtt/bog)', treatment: 'KEEP + REVIEW', ids: ['choice_lamb_shoulder_stew', 'lamb_shank', 'lamb_farikal', 'lamb_boneless'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Pecorino', treatment: 'KEEP', ids: ['r132'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Garam masala', treatment: 'KEEP', ids: ['r133'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Mascarpone', treatment: 'KEEP', ids: ['r134'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Kremost', treatment: 'KEEP', ids: ['r135'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Vaniljestang', treatment: 'KEEP + WHOLE_UNIT', ids: ['r136'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Blåskjell', treatment: 'KEEP', ids: ['r137'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Svarte bønner', treatment: 'KEEP', ids: ['r138'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Kidneybønner', treatment: 'KEEP', ids: ['r139'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Chorizo', treatment: 'KEEP', ids: ['r140'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Vaniljeis', treatment: 'KEEP', ids: ['r141'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Eple', treatment: 'KEEP + WHOLE_UNIT', ids: ['r142'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Risottoris/arborioris', treatment: 'KEEP + REVIEW', ids: ['risotto_rice', 'rice_arborio'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Aubergine', treatment: 'KEEP + WHOLE_UNIT', ids: ['r144'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Cayennepepper', treatment: 'KEEP', ids: ['r145'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Estragon', treatment: 'KEEP + PURCHASE_FORM + REVIEW', ids: ['tarragon_unspecified', 'tarragon_fresh', 'tarragon_dried'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Kjøttkraft (generisk)', treatment: 'KEEP + NOT_PURCHASED', ids: ['stock_meat', 'bouillon_meat_cube', 'compound_cooking_stock_topup'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Salsiccia', treatment: 'KEEP', ids: ['r148'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Krydder (salt og pepper, samlet)', treatment: 'KEEP + PANTRY', ids: ['compound_salt_pepper'], pantry: 'Delvis; se produktliste', confidence: 'HIGH' },
  { name: 'Squash', treatment: 'KEEP + WHOLE_UNIT', ids: ['r150'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Appelsin', treatment: 'KEEP + WHOLE_UNIT + YIELD_CONVERSION + REVIEW', ids: ['orange', 'orange_juice'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Karripulver', treatment: 'KEEP + REVIEW', ids: ['curry_unspecified', 'curry_powder_mild', 'yellow_curry_paste'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Gnocchi', treatment: 'KEEP + REVIEW', ids: ['gnocchi_unspecified', 'gnocchi_potato', 'gnocchi_potato_fresh', 'gnocchi_fresh'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Kalvekjøtt', treatment: 'KEEP + REVIEW', ids: ['veal_fillet', 'veal_shank', 'veal_schnitzel', 'veal_roast'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Peanøtter', treatment: 'KEEP', ids: ['peanut_unsalted', 'peanut_butter', 'peanut_roasted', 'peanut'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Crème fraîche', treatment: 'KEEP', ids: ['r156'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Mais', treatment: 'KEEP + REVIEW', ids: ['r157'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Svinenakke', treatment: 'KEEP', ids: ['r158'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Mirin', treatment: 'KEEP', ids: ['r159'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Pak choi', treatment: 'KEEP + WHOLE_UNIT', ids: ['r160'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Ketchup', treatment: 'KEEP', ids: ['r161'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Bringebær', treatment: 'KEEP', ids: ['raspberry', 'raspberry_fresh'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Tzatziki', treatment: 'KEEP', ids: ['r163'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Jalapeño', treatment: 'KEEP', ids: ['r164'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Potetmel', treatment: 'KEEP', ids: ['r165'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Naan', treatment: 'KEEP', ids: ['r166'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Hvitvinseddik', treatment: 'KEEP', ids: ['r167'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Blomkål', treatment: 'KEEP + WHOLE_UNIT', ids: ['r168'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Marsala', treatment: 'KEEP + REVIEW', ids: ['marsala', 'choice_kahlua_marsala_rum'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Gul sennep/grov sennep', treatment: 'KEEP', ids: ['mustard_yellow', 'mustard_wholegrain'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Kikerter', treatment: 'KEEP', ids: ['r171'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Kveitefilet', treatment: 'KEEP', ids: ['r172'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Pinjekjerner', treatment: 'KEEP + REVIEW', ids: ['pinenuts_roasted', 'pinenuts'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Eggnudler/risnudler', treatment: 'KEEP', ids: ['noodles_egg', 'noodles_rice'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Østerssaus', treatment: 'KEEP', ids: ['r175'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Favabønner/butter beans', treatment: 'KEEP + REVIEW', ids: ['fava_beans', 'butter_beans'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Kakaopulver', treatment: 'KEEP', ids: ['r177'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Baguette', treatment: 'KEEP + REVIEW', ids: ['baguette_small', 'baguette'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Romanosalat', treatment: 'KEEP + WHOLE_UNIT', ids: ['r179'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Tunfisk', treatment: 'KEEP + REVIEW', ids: ['tuna_canned_oliveoil', 'tuna_unspecified', 'tuna_canned_oil'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Lønnesirup', treatment: 'KEEP', ids: ['r181'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Pancetta', treatment: 'KEEP', ids: ['r182'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Chèvre/geitost', treatment: 'KEEP + REVIEW', ids: ['r183'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Blåmuggost', treatment: 'KEEP', ids: ['r184'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Guanciale', treatment: 'KEEP', ids: ['r185'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Druer', treatment: 'KEEP', ids: ['r186'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Melkesjokolade', treatment: 'KEEP', ids: ['r187'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Kefir', treatment: 'KEEP', ids: ['r188'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Granateple', treatment: 'KEEP + REVIEW', ids: ['pomegranate_seeds', 'pomegranate_molasses'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Kjøttdeig (kylling)', treatment: 'KEEP', ids: ['r190'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Havregryn', treatment: 'KEEP', ids: ['r191'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Hummus', treatment: 'KEEP', ids: ['r192'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Cognac', treatment: 'KEEP', ids: ['r193'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Einebær', treatment: 'KEEP', ids: ['r194'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Viltkraft/oksekraft', treatment: 'KEEP + REVIEW', ids: ['choice_r195'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Jordbær', treatment: 'KEEP', ids: ['r196'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Allehånde', treatment: 'KEEP', ids: ['r197'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Sumak', treatment: 'KEEP', ids: ['r198'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Kamskjell', treatment: 'KEEP', ids: ['r199'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Kimchi', treatment: 'KEEP', ids: ['r200'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Sellerirot', treatment: 'KEEP + WHOLE_UNIT', ids: ['r201'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Lammecarré', treatment: 'KEEP', ids: ['r202'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Pastinakk', treatment: 'KEEP + WHOLE_UNIT', ids: ['r203'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Kålrot', treatment: 'KEEP + WHOLE_UNIT', ids: ['r204'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Tofu', treatment: 'KEEP', ids: ['r205'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Andebryst/and', treatment: 'KEEP + NOT_PURCHASED', ids: ['duck_breast_skin', 'duck_fat', 'duck_leg_confit'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Pære', treatment: 'KEEP + WHOLE_UNIT', ids: ['r207'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Chipotlepaste/-adobo', treatment: 'KEEP + REVIEW', ids: ['chipotle_paste', 'chipotle_adobo'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Fennikel', treatment: 'KEEP + WHOLE_UNIT', ids: ['fennel_bulb', 'fennel_seed'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Salsa', treatment: 'KEEP + REVIEW', ids: ['salsa_unspecified', 'salsa_verde'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Rødkål', treatment: 'KEEP', ids: ['r211'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Salvie', treatment: 'KEEP + PURCHASE_FORM + REVIEW', ids: ['sage_fresh'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Pitabrød', treatment: 'KEEP', ids: ['pita', 'pita_greek'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Ytrefilet av storfe', treatment: 'KEEP + REVIEW', ids: ['beef_sirloin', 'choice_beef_sirloin_ribeye'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Gjær', treatment: 'KEEP', ids: ['yeast_dry', 'yeast_fresh'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Linser', treatment: 'KEEP', ids: ['lentils_red', 'lentils_green_cooked'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Flatbrød/persisk brød', treatment: 'KEEP', ids: ['flatbread_persian', 'flatbread_unspecified'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Miso', treatment: 'KEEP + REVIEW', ids: ['miso_light', 'miso_unspecified'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Kjøttdeig (lam)', treatment: 'KEEP', ids: ['r219'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Kjøttpølse', treatment: 'KEEP', ids: ['sausage_mild_smoked', 'sausage_meat_unspecified'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Seifilet', treatment: 'KEEP + REVIEW', ids: ['pollock_fillet', 'choice_cod_pollock'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Cannellinibønner', treatment: 'KEEP', ids: ['r222'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Berberis', treatment: 'KEEP + REVIEW', ids: ['barberry_unspecified', 'barberry_dried'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Kaffe/espresso', treatment: 'KEEP + REVIEW', ids: ['coffee_brewed', 'espresso_powder'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Kashk', treatment: 'KEEP', ids: ['r225'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Shaoxing-vin', treatment: 'KEEP', ids: ['r226'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Cajun-krydder', treatment: 'KEEP', ids: ['r227'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Kirsebær', treatment: 'KEEP', ids: ['r228'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Hoisinsaus', treatment: 'KEEP', ids: ['r229'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Bao buns', treatment: 'KEEP', ids: ['r230'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Bær (uspesifisert)', treatment: 'KEEP + REVIEW', ids: ['r231'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'BBQ-saus', treatment: 'KEEP', ids: ['r232'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Butterdeig', treatment: 'KEEP', ids: ['r233'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Næringsgjær', treatment: 'KEEP', ids: ['r234'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Frank\'s RedHot (hot sauce)', treatment: 'KEEP', ids: ['r235'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Harissa', treatment: 'KEEP', ids: ['r236'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Appelsinlikør (Grand Marnier)', treatment: 'KEEP', ids: ['r237'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Sake', treatment: 'KEEP', ids: ['r238'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Skinke (kokt/røkt)', treatment: 'KEEP', ids: ['r239'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Vinblader (i lake)', treatment: 'KEEP', ids: ['r240'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'English muffins', treatment: 'KEEP', ids: ['r241'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Enchiladasaus', treatment: 'KEEP', ids: ['r242'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Falafel', treatment: 'KEEP', ids: ['r243'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Tahini', treatment: 'KEEP', ids: ['r244'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Reinsdyrskav', treatment: 'KEEP', ids: ['r245'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Øl', treatment: 'KEEP', ids: ['r246'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Malteddik', treatment: 'KEEP', ids: ['r247'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Sherryeddik', treatment: 'KEEP', ids: ['r248'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Brioche (brød, skiver)', treatment: 'KEEP', ids: ['r249'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Bukkehornkløver', treatment: 'KEEP + REVIEW', ids: ['r250'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Sambal', treatment: 'KEEP', ids: ['r251'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Vannmelon', treatment: 'KEEP', ids: ['r252'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Ananas', treatment: 'KEEP + REVIEW', ids: ['r253'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Remulade', treatment: 'KEEP', ids: ['r254'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Hummer', treatment: 'KEEP + REVIEW', ids: ['r255'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Aioli', treatment: 'KEEP', ids: ['r256'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Japansk curryroux', treatment: 'KEEP', ids: ['r257'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Hasselnøtter', treatment: 'KEEP', ids: ['r258'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Kardemomme', treatment: 'KEEP', ids: ['r259'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Tørkede plommer (sviske)', treatment: 'KEEP', ids: ['r260'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Gelatinplater', treatment: 'KEEP', ids: ['r261'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Kokosflak', treatment: 'KEEP', ids: ['r262'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Reker', treatment: 'KEEP', ids: ['r263'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Tortellini (fersk, med ost)', treatment: 'KEEP', ids: ['r264'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Hjortekjøtt', treatment: 'KEEP', ids: ['r265'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Sichuanpepper', treatment: 'KEEP', ids: ['r266'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Kinesisk svart eddik', treatment: 'KEEP', ids: ['r267'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Champagne/musserende vin', treatment: 'KEEP + REVIEW', ids: ['choice_r268'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Reddik', treatment: 'KEEP + WHOLE_UNIT', ids: ['r269'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Cashewnøtter', treatment: 'KEEP', ids: ['r270'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Thai-krydder', treatment: 'KEEP', ids: ['r271'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Lammekraft', treatment: 'KEEP + REVIEW', ids: ['choice_r272'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Hjerteskjell', treatment: 'KEEP', ids: ['r273'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Rødbete', treatment: 'KEEP', ids: ['r274'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Digestive-kjeks', treatment: 'KEEP', ids: ['r275'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Gyoza', treatment: 'KEEP', ids: ['r276'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Ponzu', treatment: 'KEEP', ids: ['r277'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Chiliolje', treatment: 'KEEP', ids: ['r278'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Ørretfilet', treatment: 'KEEP', ids: ['r279'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Skreifilet', treatment: 'KEEP', ids: ['r280'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Paellaris', treatment: 'KEEP', ids: ['r281'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Paneer', treatment: 'KEEP', ids: ['r282'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Ghee', treatment: 'KEEP + REVIEW', ids: ['choice_r283'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Breiflabbfilet', treatment: 'KEEP', ids: ['r284'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Urter (uspesifisert)', treatment: 'KEEP + REVIEW', ids: ['r285'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Matfløte', treatment: 'KEEP', ids: ['r286'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Blåbær', treatment: 'KEEP', ids: ['r287'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Sushiris', treatment: 'KEEP', ids: ['r288'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Edamamebønner', treatment: 'KEEP', ids: ['r289'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Tynnribbe', treatment: 'KEEP', ids: ['r290'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Cottage cheese', treatment: 'KEEP', ids: ['r291'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Proteinpulver', treatment: 'KEEP + REVIEW', ids: ['r292'], pantry: 'Nei', confidence: 'LOW' },
  { name: 'Eplejuice', treatment: 'KEEP', ids: ['r293'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Vodka', treatment: 'KEEP', ids: ['r294'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Nduja', treatment: 'KEEP', ids: ['r295'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Rogn', treatment: 'KEEP', ids: ['r296'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Camembert', treatment: 'KEEP', ids: ['r297'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Makrellfilet', treatment: 'KEEP', ids: ['r298'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Uerfilet', treatment: 'KEEP', ids: ['r299'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Dadler', treatment: 'KEEP', ids: ['r300'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Kjøttdeig (svin)', treatment: 'KEEP', ids: ['r301'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Calvados', treatment: 'KEEP', ids: ['r302'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Svinekam', treatment: 'KEEP', ids: ['r303'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Savoiardi (kjeks)', treatment: 'KEEP', ids: ['r304'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Grønnkål', treatment: 'KEEP', ids: ['r305'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Trøffelprodukter', treatment: 'KEEP', ids: ['r306'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Karvefrø', treatment: 'KEEP', ids: ['r307'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Sitrongress', treatment: 'KEEP + WHOLE_UNIT', ids: ['r308'], pantry: 'Nei', confidence: 'HIGH' },
  { name: 'Bønnespirer', treatment: 'KEEP', ids: ['r309'], pantry: 'Nei', confidence: 'HIGH' },
];
